import { Rarity } from '@prisma/client';
import type { ConsumableSeedData } from '../seed-types';

/**
 * Pocoes vendidas pela Mara.
 * As faixas de acesso evitam saltos de custo entre tiers e mantem as pocoes
 * antigas utilizaveis, mas progressivamente menos eficientes.
 */
export const consumableDefinitions: ConsumableSeedData[] = [
  {
    name: 'Passe Premium de 30 dias',
    slug: 'passe-premium-30-dias',
    description:
      'Ative pela mochila para adicionar 30 dias de Premium a toda a conta.',
    tier: 1,
    rarity: Rarity.LEGENDARY,
    family: 'Passe Premium',
    healFlat: 0,
    healPercent: 0,
    minTier: 1,
    maxTier: 10,
    isSellable: false,
    isTradable: true,
    usableInCombat: false,
    usableOutOfCombat: true,
  },
  {
    name: 'Poção de Vida Menor de Aprendiz',
    description:
      'Poção inicial vinculada ao personagem. Recupera uma pequena quantidade de HP e não pode ser vendida.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Poção de Vida',
    healFlat: 40,
    healPercent: 0,
    minTier: 1,
    maxTier: 1,
    isSellable: false,
    isTradable: false,
  },
  {
    name: 'Poção de Vida Menor',
    description: 'Recupera uma pequena quantidade de HP.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Poção de Vida',
    healFlat: 40,
    healPercent: 0,
    minTier: 1,
    maxTier: 1,
  },
  {
    name: 'Poção de Vida Leve',
    description: 'Recupera uma quantidade leve de HP.',
    tier: 2,
    rarity: Rarity.UNCOMMON,
    family: 'Poção de Vida',
    healFlat: 100,
    healPercent: 4,
    minTier: 2,
    maxTier: 2,
  },
  {
    name: 'Poção de Vida',
    description: 'Recupera uma quantidade moderada de HP.',
    tier: 2,
    rarity: Rarity.UNCOMMON,
    family: 'Poção de Vida',
    healFlat: 120,
    healPercent: 6,
    minTier: 3,
    maxTier: 4,
  },
  {
    name: 'Poção de Vida Maior',
    description: 'Recupera uma boa quantidade de HP.',
    tier: 3,
    rarity: Rarity.RARE,
    family: 'Poção de Vida',
    healFlat: 300,
    healPercent: 18,
    minTier: 5,
    maxTier: 6,
  },
  {
    name: 'Poção de Vida Superior',
    description: 'Recupera uma alta quantidade de HP.',
    tier: 4,
    rarity: Rarity.EPIC,
    family: 'Poção de Vida',
    healFlat: 450,
    healPercent: 24,
    minTier: 7,
    maxTier: 8,
  },
  {
    name: 'Poção de Vida Suprema',
    description: 'Recupera uma quantidade extrema de HP.',
    tier: 5,
    rarity: Rarity.LEGENDARY,
    family: 'Poção de Vida',
    healFlat: 650,
    healPercent: 32,
    minTier: 9,
    maxTier: 10,
  },
];
