import {
  AvatarPresentation,
  AvatarRepresentation,
  CosmeticAccessType,
  CosmeticType,
  Rarity,
} from '@prisma/client';
import { additionalCosmeticAvatarDefinitions } from './cosmetic-avatar-matrix.seed-data';

export interface CosmeticCollectionSeedData {
  key: string;
  name: string;
  description: string;
  coverAssetKey?: string;
  sortOrder: number;
}

export interface CosmeticSeedData {
  key: string;
  name: string;
  description: string;
  type: CosmeticType;
  accessType: CosmeticAccessType;
  rarity: Rarity;
  collectionKey: string;
  className?: string;
  assetKey?: string;
  effectPreset?: string;
  displayText?: string;
  accentColor?: string;
  avatarPresentation?: AvatarPresentation;
  avatarRepresentation?: AvatarRepresentation;
  representationLabel?: string;
  sortOrder: number;
}

export const cosmeticCollectionDefinitions: CosmeticCollectionSeedData[] = [
  {
    key: 'acervo-do-abrigo',
    name: 'Acervo do Abrigo',
    description:
      'Aparências utilitárias recuperadas por Vera e disponíveis por Gold.',
    coverAssetKey: 'banner-acervo-bancada-manutencao',
    sortOrder: 5,
  },
  {
    key: 'cash-depois-da-lei',
    name: 'Depois da Lei',
    description:
      'Coleção Premium permanente de patrulha, estrada e refúgios fortificados, disponível por Cash no Ateliê da Vera.',
    coverAssetKey: 'banner-depois-da-lei-ultima-patrulha',
    sortOrder: 6,
  },
  {
    key: 'cash-chuva-quarentena',
    name: 'Chuva de Quarentena',
    description:
      'Coleção Premium permanente de operações urbanas sob chuva, disponível por Cash no Ateliê da Vera.',
    coverAssetKey: 'banner-chuva-quarentena-posto-emergencia',
    sortOrder: 7,
  },
  {
    key: 'premium-ultimo-abrigo',
    name: 'Último Abrigo',
    description:
      'Identidade visual Premium com tecnologia recuperada e sinais verdes de operação.',
    coverAssetKey: 'banner-premium-ultimo-abrigo',
    sortOrder: 10,
  },
  {
    key: 'premium-nucleo-helix',
    name: 'Núcleo Helix',
    description:
      'Pacote cosmético permanente de biotecnologia em cerâmica clara, obsidiana e sinais ciano-violeta.',
    coverAssetKey: 'banner-helix-nucleo-vivo',
    sortOrder: 11,
  },
  {
    key: 'premium-protocolo-carmesim',
    name: 'Protocolo Carmesim',
    description:
      'Pacote cosmético permanente de comando com blindagem grafite, marfim e energia rubra.',
    coverAssetKey: 'banner-carmesim-sala-de-guerra',
    sortOrder: 12,
  },
];

export const retiredCosmeticCollectionKeys = [
  'fundadores-alpha',
  'temporada-01-quarentena',
] as const;

const rawCosmeticDefinitions: CosmeticSeedData[] = [
  {
    key: 'avatar-acervo-vigia-oficina',
    name: 'Vigia da Oficina',
    description: 'Retrato masculino de um sobrevivente da manutenção.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.UNCOMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'avatar-acervo-vigia-oficina',
    accentColor: '#b58b4a',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Latino',
    sortOrder: 10,
  },
  {
    key: 'avatar-acervo-batedora-patio',
    name: 'Batedora do Pátio',
    description: 'Retrato feminino de uma batedora do abrigo.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.UNCOMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'avatar-acervo-batedora-patio',
    accentColor: '#579b91',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.BLACK,
    sortOrder: 20,
  },
  {
    key: 'moldura-acervo-chapa-rebitada',
    name: 'Chapa Rebitada',
    description: 'Moldura de metal reaproveitado com cantos reforçados.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'frame-shelter-riveted-plate',
    accentColor: '#9aa28e',
    sortOrder: 30,
  },
  {
    key: 'moldura-acervo-lona-marcada',
    name: 'Lona Marcada',
    description: 'Acabamento de lona costurada usado no inventário.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'frame-shelter-marked-canvas',
    accentColor: '#b39763',
    sortOrder: 40,
  },
  {
    key: 'banner-acervo-bancada-manutencao',
    name: 'Bancada de Manutenção',
    description: 'Uma bancada simples e funcional para o cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'banner-acervo-bancada-manutencao',
    accentColor: '#b58b4a',
    sortOrder: 50,
  },
  {
    key: 'banner-acervo-corredor-almoxarifado',
    name: 'Corredor do Almoxarifado',
    description: 'O corredor de suprimentos aplicado ao cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'banner-acervo-corredor-almoxarifado',
    accentColor: '#668a89',
    sortOrder: 60,
  },
  {
    key: 'fundo-acervo-oficina-abrigo',
    name: 'Oficina do Abrigo',
    description: 'Garagem de manutenção aplicada à visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.UNCOMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'background-acervo-oficina-abrigo',
    accentColor: '#a8844d',
    sortOrder: 70,
  },
  {
    key: 'fundo-acervo-patio-triagem',
    name: 'Pátio de Triagem',
    description: 'Área de separação de suprimentos para a visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.UNCOMMON,
    collectionKey: 'acervo-do-abrigo',
    assetKey: 'background-acervo-patio-triagem',
    accentColor: '#688d87',
    sortOrder: 80,
  },
  {
    key: 'efeito-acervo-poeira-oficina',
    name: 'Poeira de Oficina',
    description: 'Partículas discretas atravessam o cartão do personagem.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    effectPreset: 'workshop-dust',
    accentColor: '#c0a064',
    sortOrder: 90,
  },
  {
    key: 'efeito-acervo-pulso-lanterna',
    name: 'Pulso de Lanterna',
    description: 'Um facho suave percorre o perfil em intervalos regulares.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.UNCOMMON,
    collectionKey: 'acervo-do-abrigo',
    effectPreset: 'flashlight-sweep',
    accentColor: '#80aaa4',
    sortOrder: 100,
  },
  {
    key: 'titulo-acervo-mao-na-massa',
    name: 'Mão na Massa',
    description: 'Título de quem mantém o abrigo funcionando.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    displayText: 'Mão na Massa',
    accentColor: '#c0a064',
    sortOrder: 110,
  },
  {
    key: 'distintivo-acervo-mm',
    name: 'Distintivo MM',
    description: 'Selo público da manutenção do abrigo.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    displayText: 'MM',
    accentColor: '#c0a064',
    sortOrder: 120,
  },
  {
    key: 'titulo-acervo-olho-vigia',
    name: 'Olho de Vigia',
    description: 'Título de quem protege o perímetro.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    displayText: 'Olho de Vigia',
    accentColor: '#77a59e',
    sortOrder: 130,
  },
  {
    key: 'distintivo-acervo-ov',
    name: 'Distintivo OV',
    description: 'Selo público dos vigias do abrigo.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.COMMON,
    collectionKey: 'acervo-do-abrigo',
    displayText: 'OV',
    accentColor: '#77a59e',
    sortOrder: 140,
  },
  {
    key: 'avatar-depois-da-lei-xerife-asfalto',
    name: 'Rick Grimes',
    description: 'Retrato Premium de Rick Grimes após anos na estrada.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'avatar-depois-da-lei-xerife-asfalto',
    accentColor: '#d49b48',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.WHITE,
    sortOrder: 10,
  },
  {
    key: 'avatar-depois-da-lei-patrulheiro-ruina',
    name: 'Shane Walsh',
    description: 'Retrato Premium de Shane Walsh em patrulha de sobrevivência.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'avatar-depois-da-lei-patrulheiro-ruina',
    accentColor: '#6e9eaa',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Mediterrâneo',
    sortOrder: 20,
  },
  {
    key: 'moldura-depois-da-lei-estrela-quebrada',
    name: 'Estrela Quebrada',
    description: 'Metal de patrulha, bronze gasto e sinais de sobrevivência.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'frame-after-law-broken-star',
    accentColor: '#d49b48',
    sortOrder: 30,
  },
  {
    key: 'moldura-depois-da-lei-cerco-aco',
    name: 'Cerco de Aço',
    description: 'Moldura Premium de contenção reforçada e luz fria.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'frame-after-law-steel-siege',
    accentColor: '#6e9eaa',
    sortOrder: 40,
  },
  {
    key: 'banner-depois-da-lei-ultima-patrulha',
    name: 'Última Patrulha',
    description: 'Posto rodoviário abandonado aplicado ao cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'banner-depois-da-lei-ultima-patrulha',
    accentColor: '#d49b48',
    sortOrder: 50,
  },
  {
    key: 'banner-depois-da-lei-patio-quarentena',
    name: 'Pátio da Quarentena',
    description: 'Complexo fortificado aplicado ao cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'banner-depois-da-lei-patio-quarentena',
    accentColor: '#9f6755',
    sortOrder: 60,
  },
  {
    key: 'fundo-depois-da-lei-rodovia-silenciosa',
    name: 'Rodovia Silenciosa',
    description: 'A rota de evacuação esquecida aplicada à visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'background-depois-da-lei-rodovia-silenciosa',
    accentColor: '#d49b48',
    sortOrder: 70,
  },
  {
    key: 'fundo-depois-da-lei-refugio-colina',
    name: 'Refúgio da Colina',
    description: 'Uma fazenda fortificada aplicada à visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    assetKey: 'background-depois-da-lei-refugio-colina',
    accentColor: '#86a072',
    sortOrder: 80,
  },
  {
    key: 'efeito-depois-da-lei-cinzas-lei',
    name: 'Cinzas da Lei',
    description: 'Brasas e cinzas douradas atravessam o perfil.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    effectPreset: 'law-ashes',
    accentColor: '#d49b48',
    sortOrder: 90,
  },
  {
    key: 'efeito-depois-da-lei-pulso-cerco',
    name: 'Pulso de Cerco',
    description: 'Luzes de alerta e faíscas percorrem o perfil.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    effectPreset: 'siege-pulse',
    accentColor: '#6e9eaa',
    sortOrder: 100,
  },
  {
    key: 'titulo-depois-da-lei-ultimo-xerife',
    name: 'Último Xerife',
    description: 'Título público de comando na estrada.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    displayText: 'Último Xerife',
    accentColor: '#d49b48',
    sortOrder: 110,
  },
  {
    key: 'distintivo-depois-da-lei-ux',
    name: 'Insígnia UX',
    description: 'Distintivo público dos últimos patrulheiros da estrada.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    displayText: 'UX',
    accentColor: '#d49b48',
    sortOrder: 120,
  },
  {
    key: 'titulo-depois-da-lei-sem-recuo',
    name: 'Sem Recuo',
    description: 'Título público de quem sustenta o cerco.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    displayText: 'Sem Recuo',
    accentColor: '#6e9eaa',
    sortOrder: 130,
  },
  {
    key: 'distintivo-depois-da-lei-sr',
    name: 'Insígnia SR',
    description: 'Distintivo público dos sobreviventes do cerco.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-depois-da-lei',
    displayText: 'SR',
    accentColor: '#6e9eaa',
    sortOrder: 140,
  },
  {
    key: 'avatar-chuva-quarentena-leon',
    name: 'Leon',
    description: 'Retrato Premium de Leon em operação sob chuva intensa.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    assetKey: 'avatar-chuva-quarentena-leon',
    accentColor: '#b7d9e8',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.WHITE,
    sortOrder: 10,
  },
  {
    key: 'moldura-chuva-quarentena-protocolo-rpd',
    name: 'Protocolo R.P.D.',
    description: 'Aço operacional, branco gasto e alerta escarlate.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    assetKey: 'frame-quarantine-rpd',
    accentColor: '#c9444c',
    sortOrder: 20,
  },
  {
    key: 'banner-chuva-quarentena-posto-emergencia',
    name: 'Posto de Emergência',
    description: 'Um posto operacional encharcado aplicado ao cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    assetKey: 'banner-chuva-quarentena-posto-emergencia',
    accentColor: '#b7d9e8',
    sortOrder: 30,
  },
  {
    key: 'fundo-chuva-quarentena-cidade-encharcada',
    name: 'Cidade Encharcada',
    description: 'Uma avenida isolada sob chuva aplicada à visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    assetKey: 'background-chuva-quarentena-cidade-encharcada',
    accentColor: '#91bfd2',
    sortOrder: 40,
  },
  {
    key: 'efeito-chuva-quarentena-tempestade',
    name: 'Chuva de Quarentena',
    description: 'Gotas frias e reflexos escarlates atravessam o perfil.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    effectPreset: 'quarantine-rain',
    accentColor: '#b7d9e8',
    sortOrder: 50,
  },
  {
    key: 'titulo-chuva-quarentena-agente-quarentena',
    name: 'Agente da Quarentena',
    description: 'Título público de quem atravessa a cidade sob tempestade.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    displayText: 'Agente da Quarentena',
    accentColor: '#b7d9e8',
    sortOrder: 60,
  },
  {
    key: 'distintivo-chuva-quarentena-aq',
    name: 'Insígnia AQ',
    description: 'Distintivo público dos agentes da zona de quarentena.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.ENTITLEMENT,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'cash-chuva-quarentena',
    displayText: 'AQ',
    accentColor: '#c9444c',
    sortOrder: 70,
  },
  {
    key: 'avatar-premium-lutador-vanguarda',
    name: 'Vanguarda do Abrigo',
    description: 'Retrato Premium exclusivo para Lutador.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    className: 'Lutador',
    assetKey: 'avatar-premium-lutador-vanguarda',
    accentColor: '#72d94c',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.WHITE,
    sortOrder: 10,
  },
  {
    key: 'avatar-premium-assassino-espectro',
    name: 'Espectro do Perímetro',
    description: 'Retrato Premium exclusivo para Assassino.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    className: 'Assassino',
    assetKey: 'avatar-premium-assassino-espectro',
    accentColor: '#72d94c',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.WHITE,
    sortOrder: 14,
  },
  {
    key: 'avatar-premium-atirador-sentinela',
    name: 'Sentinela da Muralha',
    description: 'Retrato Premium exclusivo para Atirador.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    className: 'Atirador',
    assetKey: 'avatar-premium-atirador-sentinela',
    accentColor: '#72d94c',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Latino',
    sortOrder: 13,
  },
  {
    key: 'avatar-premium-medico-biooperador',
    name: 'Bio-operador de Campo',
    description: 'Retrato Premium exclusivo para Médico.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    className: 'Médico',
    assetKey: 'avatar-premium-medico-biooperador',
    accentColor: '#72d94c',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Latina',
    sortOrder: 17,
  },
  {
    key: 'moldura-premium-sinal-verde',
    name: 'Sinal Verde',
    description: 'Moldura operacional animada do Último Abrigo.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    assetKey: 'frame-premium-signal-green',
    accentColor: '#72d94c',
    sortOrder: 20,
  },
  {
    key: 'banner-premium-centro-comando',
    name: 'Centro de Comando',
    description: 'Fundo do cartão público do personagem.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    assetKey: 'banner-premium-ultimo-abrigo',
    accentColor: '#72d94c',
    sortOrder: 30,
  },
  {
    key: 'fundo-premium-ultimo-abrigo',
    name: 'Último Abrigo',
    description: 'Cenário de fundo aplicado à visão geral do personagem.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.EPIC,
    collectionKey: 'premium-ultimo-abrigo',
    assetKey: 'background-premium-ultimo-abrigo',
    accentColor: '#72d94c',
    sortOrder: 40,
  },
  {
    key: 'efeito-premium-varredura',
    name: 'Varredura Operacional',
    description: 'Pulso luminoso discreto no cartão do personagem.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.RARE,
    collectionKey: 'premium-ultimo-abrigo',
    effectPreset: 'signal-scan',
    accentColor: '#72d94c',
    sortOrder: 50,
  },
  {
    key: 'titulo-premium-sobrevivente',
    name: 'Sobrevivente Premium',
    description: 'Título exibido abaixo do nome do personagem.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.RARE,
    collectionKey: 'premium-ultimo-abrigo',
    displayText: 'Sobrevivente Premium',
    accentColor: '#72d94c',
    sortOrder: 60,
  },
  {
    key: 'distintivo-premium-p',
    name: 'Distintivo Premium',
    description: 'Selo público de assinatura ativa.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.RARE,
    collectionKey: 'premium-ultimo-abrigo',
    displayText: 'P',
    accentColor: '#72d94c',
    sortOrder: 70,
  },
  {
    key: 'avatar-helix-lutador-baluarte',
    name: 'Baluarte Helix',
    description: 'Retrato lendário do Núcleo Helix para Lutador.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    className: 'Lutador',
    assetKey: 'avatar-helix-lutador-baluarte',
    accentColor: '#65d8e8',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.BLACK,
    sortOrder: 16,
  },
  {
    key: 'avatar-helix-assassino-espectro',
    name: 'Espectro Helix',
    description: 'Retrato lendário do Núcleo Helix para Assassino.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    className: 'Assassino',
    assetKey: 'avatar-helix-assassino-espectro',
    accentColor: '#65d8e8',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.JAPANESE,
    sortOrder: 15,
  },
  {
    key: 'avatar-helix-atirador-vidente',
    name: 'Vidente Helix',
    description: 'Retrato lendário do Núcleo Helix para Atirador.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    className: 'Atirador',
    assetKey: 'avatar-helix-atirador-vidente',
    accentColor: '#65d8e8',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Latino',
    sortOrder: 13,
  },
  {
    key: 'avatar-helix-medico-guardavida',
    name: 'Guardavida Helix',
    description: 'Retrato lendário do Núcleo Helix para Médico.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    className: 'Médico',
    assetKey: 'avatar-helix-medico-guardavida',
    accentColor: '#65d8e8',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Sul-asiática',
    sortOrder: 17,
  },
  {
    key: 'moldura-helix-orbita',
    name: 'Órbita Helix',
    description: 'Moldura orbital ciano-violeta do Núcleo Helix.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    assetKey: 'frame-helix-orbit',
    accentColor: '#65d8e8',
    sortOrder: 20,
  },
  {
    key: 'banner-helix-nucleo-vivo',
    name: 'Núcleo Vivo',
    description: 'Laboratório Helix aplicado ao cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    assetKey: 'banner-helix-nucleo-vivo',
    accentColor: '#65d8e8',
    sortOrder: 30,
  },
  {
    key: 'fundo-helix-observatorio',
    name: 'Observatório Helix',
    description: 'Observatório biotecnológico para a visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    assetKey: 'background-helix-observatorio',
    accentColor: '#65d8e8',
    sortOrder: 40,
  },
  {
    key: 'efeito-helix-orbita',
    name: 'Órbita de Diagnóstico',
    description: 'Anéis de diagnóstico percorrem o perfil em ciclos suaves.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    effectPreset: 'helix-orbit',
    accentColor: '#65d8e8',
    sortOrder: 50,
  },
  {
    key: 'titulo-helix-guardiao',
    name: 'Guardião do Núcleo',
    description: 'Título público da elite operacional Helix.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    displayText: 'Guardião do Núcleo',
    accentColor: '#65d8e8',
    sortOrder: 60,
  },
  {
    key: 'distintivo-helix-hx',
    name: 'Insígnia HX',
    description: 'Distintivo público do Núcleo Helix.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-nucleo-helix',
    displayText: 'HX',
    accentColor: '#65d8e8',
    sortOrder: 70,
  },
  {
    key: 'avatar-carmesim-lutador-egide',
    name: 'Égide Carmesim',
    description: 'Retrato lendário do Protocolo Carmesim para Lutador.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    className: 'Lutador',
    assetKey: 'avatar-carmesim-lutador-egide',
    accentColor: '#ef5a56',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.WHITE,
    sortOrder: 10,
  },
  {
    key: 'avatar-carmesim-assassino-lamina',
    name: 'Lâmina Rubra',
    description: 'Retrato lendário do Protocolo Carmesim para Assassino.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    className: 'Assassino',
    assetKey: 'avatar-carmesim-assassino-lamina',
    accentColor: '#ef5a56',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.OTHER,
    representationLabel: 'Latina',
    sortOrder: 17,
  },
  {
    key: 'avatar-carmesim-atirador-olho',
    name: 'Olho do Protocolo',
    description: 'Retrato lendário do Protocolo Carmesim para Atirador.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    className: 'Atirador',
    assetKey: 'avatar-carmesim-atirador-olho',
    accentColor: '#ef5a56',
    avatarPresentation: AvatarPresentation.FEMININE,
    avatarRepresentation: AvatarRepresentation.BLACK,
    sortOrder: 16,
  },
  {
    key: 'avatar-carmesim-medico-cirurgiao',
    name: 'Cirurgião de Ruptura',
    description: 'Retrato lendário do Protocolo Carmesim para Médico.',
    type: CosmeticType.AVATAR,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    className: 'Médico',
    assetKey: 'avatar-carmesim-medico-cirurgiao',
    accentColor: '#ef5a56',
    avatarPresentation: AvatarPresentation.MASCULINE,
    avatarRepresentation: AvatarRepresentation.JAPANESE,
    sortOrder: 11,
  },
  {
    key: 'moldura-carmesim-egide',
    name: 'Égide Rubra',
    description: 'Moldura blindada do Protocolo Carmesim.',
    type: CosmeticType.AVATAR_FRAME,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    assetKey: 'frame-crimson-aegis',
    accentColor: '#ef5a56',
    sortOrder: 20,
  },
  {
    key: 'banner-carmesim-sala-de-guerra',
    name: 'Sala de Guerra Rubra',
    description: 'Centro tático Carmesim aplicado ao cartão público.',
    type: CosmeticType.PROFILE_BANNER,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    assetKey: 'banner-carmesim-sala-de-guerra',
    accentColor: '#ef5a56',
    sortOrder: 30,
  },
  {
    key: 'fundo-carmesim-fortaleza',
    name: 'Fortaleza Carmesim',
    description: 'Bastião de quarentena aplicado à visão geral.',
    type: CosmeticType.OVERVIEW_BACKGROUND,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    assetKey: 'background-carmesim-fortaleza',
    accentColor: '#ef5a56',
    sortOrder: 40,
  },
  {
    key: 'efeito-carmesim-ruptura',
    name: 'Ruptura Carmesim',
    description:
      'Traços de energia rubra cortam o perfil em pulsos controlados.',
    type: CosmeticType.PROFILE_EFFECT,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    effectPreset: 'crimson-rift',
    accentColor: '#ef5a56',
    sortOrder: 50,
  },
  {
    key: 'titulo-carmesim-executor',
    name: 'Executor do Protocolo',
    description: 'Título público da força de comando Carmesim.',
    type: CosmeticType.TITLE,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    displayText: 'Executor do Protocolo',
    accentColor: '#ef5a56',
    sortOrder: 60,
  },
  {
    key: 'distintivo-carmesim-pc',
    name: 'Insígnia PC',
    description: 'Distintivo público do Protocolo Carmesim.',
    type: CosmeticType.BADGE,
    accessType: CosmeticAccessType.PREMIUM,
    rarity: Rarity.LEGENDARY,
    collectionKey: 'premium-protocolo-carmesim',
    displayText: 'PC',
    accentColor: '#ef5a56',
    sortOrder: 70,
  },
  ...additionalCosmeticAvatarDefinitions,
];

const PERMANENT_PACKAGE_COLLECTION_KEYS = new Set([
  'acervo-do-abrigo',
  'cash-depois-da-lei',
  'cash-chuva-quarentena',
  'premium-nucleo-helix',
  'premium-protocolo-carmesim',
]);

export const cosmeticDefinitions: CosmeticSeedData[] =
  rawCosmeticDefinitions.map((definition) =>
    PERMANENT_PACKAGE_COLLECTION_KEYS.has(definition.collectionKey)
      ? { ...definition, accessType: CosmeticAccessType.ENTITLEMENT }
      : definition,
  );
