import { ItemSlot, MaterialOrigin, Rarity } from '@prisma/client';
import type { EquipmentSeedData, MaterialSeedData } from '../seed-types';

const SUBURBIO = 'Subúrbio Silencioso';

type MaterialSeedDataWithGatheringProgression = MaterialSeedData & {
  requiredGatheringLevel?: number;
  gatheringXpPerUnit?: number;
  baseGatheringRatePerHour?: number | null;
};

export const starterEquipmentDefinitions: EquipmentSeedData[] = [
  {
    name: 'Cano Amassado',
    description:
      'Arma inicial extremamente simples, feita de um cano velho, torto e sem acabamento.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Arma Improvisada',
    className: 'Lutador',
    mapName: SUBURBIO,
    strengthBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Tábua de Defesa',
    description:
      'Tábua grossa usada como proteção improvisada nos primeiros confrontos.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.OFF_HAND,
    family: 'Escudo Improvisado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 2,
    willpowerBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Capuz Acolchoado Gasto',
    description:
      'Proteção simples para a cabeça, feita com tecido grosso e acolchoamento velho.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.HEAD,
    family: 'Capuz Acolchoado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Colete Rasgado de Rua',
    description:
      'Colete velho com camadas extras de pano, couro gasto e reforços mal costurados.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.ARMOR,
    family: 'Colete Improvisado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 2,
    isCraftable: false,
  },
  {
    name: 'Calça Grossa Remendada',
    description:
      'Calça pesada e remendada, suficiente para proteger contra arranhões e quedas leves.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.PANTS,
    family: 'Roupa Reforçada',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Botas Gastas de Quintal',
    description:
      'Botas velhas e rígidas, resistentes o bastante para os primeiros passos fora do abrigo.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.BOOTS,
    family: 'Botas Gastas',
    className: 'Lutador',
    mapName: SUBURBIO,
    willpowerBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Pistola Falhando',
    description:
      'Arma curta velha, instável e imprecisa, mas ainda funcional contra infectados fracos.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Pistola',
    className: 'Atirador',
    mapName: SUBURBIO,
    strengthBonus: 1,
    precisionBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Munhequeira de Apoio',
    description:
      'Munhequeira simples usada para firmar a mão e estabilizar a mira inicial.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.OFF_HAND,
    family: 'Munhequeira',
    className: 'Atirador',
    mapName: SUBURBIO,
    precisionBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Boné com Lente Riscada',
    description:
      'Boné adaptado com uma lente velha e arranhada para auxiliar a visada curta.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.HEAD,
    family: 'Boné de Mira',
    className: 'Atirador',
    mapName: SUBURBIO,
    precisionBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Colete de Pano com Coldre',
    description: 'Colete leve com um coldre costurado de forma improvisada.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.ARMOR,
    family: 'Colete Leve',
    className: 'Atirador',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Calça com Bolso de Munição',
    description:
      'Calça simples com bolsos adaptados para carregar munição, trapos e peças pequenas.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.PANTS,
    family: 'Calça de Apoio',
    className: 'Atirador',
    mapName: SUBURBIO,
    agilityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Botas Leves Gastas',
    description:
      'Botas leves e gastas, usadas para movimentação rápida em áreas residenciais.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.BOOTS,
    family: 'Botas Leves',
    className: 'Atirador',
    mapName: SUBURBIO,
    agilityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Faca Lascada',
    description:
      'Lâmina curta, gasta e lascada, usada para golpes rápidos e silenciosos.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Faca',
    className: 'Assassino',
    mapName: SUBURBIO,
    strengthBonus: 1,
    precisionBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Faixa de Pulso Apertada',
    description:
      'Faixa simples que melhora a firmeza dos movimentos e reduz escorregões da mão.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.OFF_HAND,
    family: 'Faixa de Pulso',
    className: 'Assassino',
    mapName: SUBURBIO,
    agilityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Capuz Escuro Rasgado',
    description:
      'Capuz escuro e desgastado, útil para ocultação básica nas primeiras rotas.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.HEAD,
    family: 'Capuz Leve',
    className: 'Assassino',
    mapName: SUBURBIO,
    precisionBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Jaqueta Fina Escurecida',
    description: 'Jaqueta leve, fácil de mover e pouco chamativa.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.ARMOR,
    family: 'Jaqueta Leve',
    className: 'Assassino',
    mapName: SUBURBIO,
    agilityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Calça Flexível Gasta',
    description:
      'Calça leve e usada, adequada para movimentação rápida e esquiva básica.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.PANTS,
    family: 'Calça Flexível',
    className: 'Assassino',
    mapName: SUBURBIO,
    agilityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Tênis Remendado',
    description: 'Tênis velho, silencioso e fácil de usar em fuga.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.BOOTS,
    family: 'Calçado Leve',
    className: 'Assassino',
    mapName: SUBURBIO,
    agilityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Seringa de Emergência',
    description:
      'Aplicador simples usado tanto para suporte quanto para defesa básica em campo.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Aplicador Simples',
    className: 'Médico',
    mapName: SUBURBIO,
    strengthBonus: 1,
    techniqueBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Bolsa de Curativos Rasgada',
    description:
      'Bolsa médica velha com poucos recursos utilizáveis, mas ainda funcional.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.OFF_HAND,
    family: 'Bolsa Médica',
    className: 'Médico',
    mapName: SUBURBIO,
    willpowerBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Máscara Cirúrgica Gasta',
    description:
      'Máscara simples e pouco confiável, mas melhor que respirar diretamente o ar contaminado.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.HEAD,
    family: 'Máscara Simples',
    className: 'Médico',
    mapName: SUBURBIO,
    willpowerBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Jaleco Remendado',
    description:
      'Jaleco velho com reforços improvisados e manchas antigas de atendimento emergencial.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.ARMOR,
    family: 'Jaleco',
    className: 'Médico',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Calça de Plantão Gasta',
    description:
      'Calça comum de atendimento, já bastante desgastada pelo uso em campo.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.PANTS,
    family: 'Calça Médica',
    className: 'Médico',
    mapName: SUBURBIO,
    techniqueBonus: 1,
    isCraftable: false,
  },
  {
    name: 'Botas Clínicas Manchadas',
    description:
      'Botas simples de ambiente clínico, manchadas e adaptadas para deslocamento externo.',
    tier: 0,
    rarity: Rarity.COMMON,
    slot: ItemSlot.BOOTS,
    family: 'Botas Clínicas',
    className: 'Médico',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    isCraftable: false,
  },
];

export const materialDefinitions: MaterialSeedDataWithGatheringProgression[] = [
  {
    name: 'Resíduo Infecto Pálido',
    description:
      'Material raro obtido de infectados fracos do Subúrbio Silencioso.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Drop de Mob',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DROP_MOBS,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 0,
    baseGatheringRatePerHour: null,
  },
  {
    name: 'Cano de Cerca Amassado',
    description:
      'Peça principal obtida por desmanche de cercas e estruturas leves do Subúrbio Silencioso.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Lâmina de Machado Lascada',
    description:
      'Peça principal obtida por desmanche de ferramentas quebradas e sucata cortante.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Tecido Grosso de Sobrevivência',
    description:
      'Material compartilhado obtido por coleta de tecidos, lonas e retalhos resistentes.',
    tier: 1,
    family: 'Material de Coleta',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.COLETA,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Lacre Antisséptico Básico',
    description:
      'Material de contenção básica recuperado de kits, vedantes e lacres sanitários simples.',
    tier: 1,
    family: 'Material de Contenção',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.CONTENCAO,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Placa de Sucata de Garagem',
    description:
      'Peça principal obtida por desmanche de portões, garagens e chapas urbanas leves.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Placa de Cerca Entortada',
    description:
      'Peça principal obtida por desmanche de placas de cerca danificadas.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Correia de Couro Ressecado',
    description:
      'Material compartilhado obtido por coleta de cintos, tiras e couro velho.',
    tier: 1,
    family: 'Material de Coleta',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.COLETA,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Filtro de Punho Selado',
    description:
      'Material de contenção usado em defesas de punho e proteção contra contaminação leve.',
    tier: 1,
    family: 'Material de Contenção',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.CONTENCAO,
    requiredGatheringLevel: 1,
    gatheringXpPerUnit: 3,
    baseGatheringRatePerHour: 30,
  },
  {
    name: 'Lona Acolchoada de Sobrevivência',
    description:
      'Peça principal obtida por desmanche de acolchoamentos, coberturas e lonas antigas.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Casco de Couro com Borracha Remendada',
    description:
      'Peça principal obtida por desmanche de proteção improvisada de couro e borracha.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Forro de Sobrevivência',
    description:
      'Material compartilhado obtido por coleta de forros, mantas e tecidos de proteção.',
    tier: 1,
    family: 'Material de Coleta',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.COLETA,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Máscara de Contenção Rudimentar',
    description:
      'Material de contenção básica usado em proteções de cabeça de entrada.',
    tier: 1,
    family: 'Material de Contenção',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.CONTENCAO,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Chapa Torácica Gasta',
    description:
      'Peça principal obtida por desmanche de placas torácicas simples e proteções civis.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
  {
    name: 'Reforço de Sucata de Garagem',
    description:
      'Peça principal obtida por desmanche de sucata rígida e reforços improvisados.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
  {
    name: 'Tecido Civil Reforçado',
    description:
      'Material compartilhado obtido por coleta de tecidos urbanos mais resistentes.',
    tier: 1,
    family: 'Material de Coleta',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.COLETA,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Revestimento Imune Simples',
    description: 'Material de contenção usado em proteções corporais de entrada.',
    tier: 1,
    family: 'Material de Contenção',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.CONTENCAO,
    requiredGatheringLevel: 2,
    gatheringXpPerUnit: 4,
    baseGatheringRatePerHour: 26,
  },
  {
    name: 'Articulação de Liga Gasta',
    description:
      'Peça principal obtida por desmanche de articulações, dobradiças e ligas simples.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
  {
    name: 'Reforço de Sucata de Joelho',
    description:
      'Peça principal obtida por desmanche de reforços de perna e placas pequenas.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 4,
    gatheringXpPerUnit: 6,
    baseGatheringRatePerHour: 18,
  },
  {
    name: 'Lona Costurada',
    description:
      'Material compartilhado obtido por coleta de lonas, costuras e tecido grosso reaproveitado.',
    tier: 1,
    family: 'Material de Coleta',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.COLETA,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
  {
    name: 'Isolante Biológico de Perna',
    description:
      'Material de contenção aplicado em proteções inferiores contra contato infectado.',
    tier: 1,
    family: 'Material de Contenção',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.CONTENCAO,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
  {
    name: 'Solado Metálico Gasto',
    description:
      'Peça principal obtida por desmanche de solados, chapas pequenas e reforços de marcha.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 4,
    gatheringXpPerUnit: 6,
    baseGatheringRatePerHour: 18,
  },
  {
    name: 'Reforço de Borracha de Pneu',
    description:
      'Peça principal obtida por desmanche de pneus, borracha grossa e reforços de quintal.',
    tier: 1,
    family: 'Material de Desmanche',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.DESMANCHE,
    requiredGatheringLevel: 4,
    gatheringXpPerUnit: 6,
    baseGatheringRatePerHour: 18,
  },
  {
    name: 'Palmilha de Marcha',
    description:
      'Material compartilhado obtido por coleta de palmilhas, forros e apoio de caminhada.',
    tier: 1,
    family: 'Material de Coleta',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.COLETA,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
  {
    name: 'Vedação de Bota Contaminada',
    description:
      'Material de contenção usado para vedar botas contra lama, sangue e resíduos infectados.',
    tier: 1,
    family: 'Material de Contenção',
    mapName: SUBURBIO,
    materialOrigin: MaterialOrigin.CONTENCAO,
    requiredGatheringLevel: 3,
    gatheringXpPerUnit: 5,
    baseGatheringRatePerHour: 22,
  },
];

export const equipmentDefinitions: EquipmentSeedData[] = [
  {
    name: 'Maça de Cano de Cerca',
    description: 'Arma improvisada feita a partir de um cano de cerca amassado.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Maça',
    className: 'Lutador',
    mapName: SUBURBIO,
    strengthBonus: 3,
  },
  {
    name: 'Machado de Quintal Remendado',
    description:
      'Machado improvisado com lâmina lascada, tecido grosso de sobrevivência e lacre antisséptico básico.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Machado',
    className: 'Lutador',
    mapName: SUBURBIO,
    strengthBonus: 2,
    techniqueBonus: 1,
  },
  {
    name: 'Braçadeira de Couro de Garagem',
    description:
      'Braçadeira defensiva feita com couro ressecado, placa de sucata de garagem e filtro de punho selado.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.OFF_HAND,
    family: 'Braçadeira',
    className: 'Lutador',
    mapName: SUBURBIO,
    strengthBonus: 1,
    vitalityBonus: 2,
    willpowerBonus: 1,
  },
  {
    name: 'Defletor de Placa de Cerca',
    description:
      'Defesa improvisada feita com uma placa de cerca entortada, correia de couro ressecado e filtro de punho selado.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.OFF_HAND,
    family: 'Defletor',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 2,
    willpowerBonus: 2,
  },
  {
    name: 'Capacete Acolchoado de Lona Costurada',
    description:
      'Capacete simples feito com lona acolchoada de sobrevivência, forro de sobrevivência e máscara de contenção rudimentar.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.HEAD,
    family: 'Capacete Acolchoado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 2,
    willpowerBonus: 1,
  },
  {
    name: 'Capacete de Couro e Borracha de Garagem',
    description:
      'Capacete improvisado feito com casco de couro com borracha remendada, forro de sobrevivência e máscara de contenção rudimentar.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.HEAD,
    family: 'Capacete de Couro e Borracha',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    techniqueBonus: 1,
    willpowerBonus: 1,
  },
  {
    name: 'Colete de Tecido Civil Reforçado',
    description:
      'Colete de entrada feito com chapa torácica gasta, tecido civil reforçado e revestimento imune simples.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.ARMOR,
    family: 'Tecido Reforçado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 3,
    willpowerBonus: 1,
  },
  {
    name: 'Jaqueta de Couro de Garagem',
    description:
      'Jaqueta resistente feita com reforço de sucata de garagem, tecido civil reforçado e revestimento imune simples.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.ARMOR,
    family: 'Couro/Borracha',
    className: 'Lutador',
    mapName: SUBURBIO,
    strengthBonus: 1,
    vitalityBonus: 2,
    willpowerBonus: 1,
  },
  {
    name: 'Calça de Lona Costurada',
    description:
      'Calça reforçada feita com articulação de liga gasta, lona costurada e isolante biológico de perna.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.PANTS,
    family: 'Tecido Reforçado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 2,
    techniqueBonus: 1,
  },
  {
    name: 'Calça de Couro de Garagem',
    description:
      'Calça robusta feita com reforço de sucata de joelho, lona costurada e isolante biológico de perna.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.PANTS,
    family: 'Couro/Borracha',
    className: 'Lutador',
    mapName: SUBURBIO,
    strengthBonus: 1,
    vitalityBonus: 1,
    techniqueBonus: 1,
  },
  {
    name: 'Botas de Couro Costurado',
    description:
      'Botas de marcha feitas com solado metálico gasto, palmilha de marcha e vedação de bota contaminada.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.BOOTS,
    family: 'Botas de Couro Reforçado',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    techniqueBonus: 1,
  },
  {
    name: 'Botas de Borracha de Quintal',
    description:
      'Botas improvisadas com reforço de borracha de pneu, palmilha de marcha e vedação de bota contaminada.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.BOOTS,
    family: 'Botas de Borracha Industrial',
    className: 'Lutador',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    willpowerBonus: 1,
  },
  {
    name: 'Adaga de Ponta de Grade',
    description: 'Lâmina curta improvisada com uma ponta de grade afiada.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Adaga',
    className: 'Assassino',
    mapName: SUBURBIO,
    agilityBonus: 2,
    precisionBonus: 3,
  },
  {
    name: 'Pistola de Cano Encurtado',
    description:
      'Arma de fogo improvisada, instável, mas útil nos primeiros confrontos.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Pistola',
    className: 'Atirador',
    mapName: SUBURBIO,
    precisionBonus: 4,
  },
  {
    name: 'Aplicador de Campo Remendado',
    description: 'Ferramenta médica adaptada para combate e suporte em campo.',
    tier: 1,
    rarity: Rarity.COMMON,
    slot: ItemSlot.MAIN_HAND,
    family: 'Aplicador',
    className: 'Médico',
    mapName: SUBURBIO,
    vitalityBonus: 1,
    precisionBonus: 2,
    techniqueBonus: 2,
    willpowerBonus: 1,
  },
];