import { Rarity } from '@prisma/client';
import type { MobDropItemSeedData, MobDropTableSeedData } from '../seed-types';

/**
 * Itens e tabelas de drop dos mobs.
 *
 * Fonte: C:/Users/Neto/Downloads/mobs_jogo_completo (1).csv.
 * Use mapa + submapa + ordem + nome do mob como identificadores estaveis para evitar depender de IDs do banco.
 */
export const mobDropItemDefinitions: MobDropItemSeedData[] = [
  {
    name: 'Biomaterial Articular Comum',
    slug: 'biomaterial-articular-comum',
    description:
      'Biomaterial Articular obtido de mobs. Uso: Crafting por família de slot.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Biomaterial Articular',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Cortante Comum',
    slug: 'biomaterial-cortante-comum',
    description:
      'Biomaterial Cortante obtido de mobs. Uso: Crafting por família de slot.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Biomaterial Cortante',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Craniano Comum',
    slug: 'biomaterial-craniano-comum',
    description:
      'Biomaterial Craniano obtido de mobs. Uso: Crafting por família de slot.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Biomaterial Craniano',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial de Mobilidade Comum',
    slug: 'biomaterial-de-mobilidade-comum',
    description:
      'Biomaterial de Mobilidade obtido de mobs. Uso: Crafting por família de slot.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Biomaterial de Mobilidade',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Reativo Comum',
    slug: 'biomaterial-reativo-comum',
    description:
      'Biomaterial Reativo obtido de mobs. Uso: Crafting por família de slot.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Biomaterial Reativo',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Torácico Comum',
    slug: 'biomaterial-toracico-comum',
    description:
      'Biomaterial Torácico obtido de mobs. Uso: Crafting por família de slot.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Biomaterial Torácico',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Núcleo Infectado de Elite Comum',
    slug: 'nucleo-infectado-de-elite-comum',
    description:
      'Núcleo Infectado de Elite obtido de mobs. Uso: Crafting raro / upgrades de elite.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Núcleo Infectado de Elite',
    dropType: 'ELITE_CORE',
    usage: 'Crafting raro / upgrades de elite',
  },
  {
    name: 'Resíduo Infecto Pálido',
    slug: 'residuo-infecto-palido',
    description:
      'Resíduo Infecto obtido de mobs. Uso: Crafting por faixa de tier.',
    tier: 1,
    rarity: Rarity.COMMON,
    family: 'Resíduo Infecto',
    dropType: 'RESIDUE',
    usage: 'Crafting por faixa de tier',
  },
  {
    name: 'Biomaterial Articular Incomum',
    slug: 'biomaterial-articular-incomum',
    description:
      'Biomaterial Articular obtido de mobs. Uso: Crafting por família de slot.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Biomaterial Articular',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Cortante Incomum',
    slug: 'biomaterial-cortante-incomum',
    description:
      'Biomaterial Cortante obtido de mobs. Uso: Crafting por família de slot.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Biomaterial Cortante',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Craniano Incomum',
    slug: 'biomaterial-craniano-incomum',
    description:
      'Biomaterial Craniano obtido de mobs. Uso: Crafting por família de slot.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Biomaterial Craniano',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial de Mobilidade Incomum',
    slug: 'biomaterial-de-mobilidade-incomum',
    description:
      'Biomaterial de Mobilidade obtido de mobs. Uso: Crafting por família de slot.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Biomaterial de Mobilidade',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Reativo Incomum',
    slug: 'biomaterial-reativo-incomum',
    description:
      'Biomaterial Reativo obtido de mobs. Uso: Crafting por família de slot.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Biomaterial Reativo',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Torácico Incomum',
    slug: 'biomaterial-toracico-incomum',
    description:
      'Biomaterial Torácico obtido de mobs. Uso: Crafting por família de slot.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Biomaterial Torácico',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Núcleo Infectado de Elite Incomum',
    slug: 'nucleo-infectado-de-elite-incomum',
    description:
      'Núcleo Infectado de Elite obtido de mobs. Uso: Crafting raro / upgrades de elite.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Núcleo Infectado de Elite',
    dropType: 'ELITE_CORE',
    usage: 'Crafting raro / upgrades de elite',
  },
  {
    name: 'Resíduo Infecto Amarelado',
    slug: 'residuo-infecto-amarelado',
    description:
      'Resíduo Infecto obtido de mobs. Uso: Crafting por faixa de tier.',
    tier: 3,
    rarity: Rarity.UNCOMMON,
    family: 'Resíduo Infecto',
    dropType: 'RESIDUE',
    usage: 'Crafting por faixa de tier',
  },
  {
    name: 'Biomaterial Articular Raro',
    slug: 'biomaterial-articular-raro',
    description:
      'Biomaterial Articular obtido de mobs. Uso: Crafting por família de slot.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Biomaterial Articular',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Cortante Raro',
    slug: 'biomaterial-cortante-raro',
    description:
      'Biomaterial Cortante obtido de mobs. Uso: Crafting por família de slot.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Biomaterial Cortante',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Craniano Raro',
    slug: 'biomaterial-craniano-raro',
    description:
      'Biomaterial Craniano obtido de mobs. Uso: Crafting por família de slot.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Biomaterial Craniano',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Reativo Raro',
    slug: 'biomaterial-reativo-raro',
    description:
      'Biomaterial Reativo obtido de mobs. Uso: Crafting por família de slot.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Biomaterial Reativo',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Torácico Raro',
    slug: 'biomaterial-toracico-raro',
    description:
      'Biomaterial Torácico obtido de mobs. Uso: Crafting por família de slot.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Biomaterial Torácico',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Núcleo Infectado de Elite Raro',
    slug: 'nucleo-infectado-de-elite-raro',
    description:
      'Núcleo Infectado de Elite obtido de mobs. Uso: Crafting raro / upgrades de elite.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Núcleo Infectado de Elite',
    dropType: 'ELITE_CORE',
    usage: 'Crafting raro / upgrades de elite',
  },
  {
    name: 'Resíduo Infecto Tóxico',
    slug: 'residuo-infecto-toxico',
    description:
      'Resíduo Infecto obtido de mobs. Uso: Crafting por faixa de tier.',
    tier: 5,
    rarity: Rarity.RARE,
    family: 'Resíduo Infecto',
    dropType: 'RESIDUE',
    usage: 'Crafting por faixa de tier',
  },
  {
    name: 'Biomaterial de Mobilidade Raro',
    slug: 'biomaterial-de-mobilidade-raro',
    description:
      'Biomaterial de Mobilidade obtido de mobs. Uso: Crafting por família de slot.',
    tier: 6,
    rarity: Rarity.RARE,
    family: 'Biomaterial de Mobilidade',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Articular Épico',
    slug: 'biomaterial-articular-epico',
    description:
      'Biomaterial Articular obtido de mobs. Uso: Crafting por família de slot.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Biomaterial Articular',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Cortante Épico',
    slug: 'biomaterial-cortante-epico',
    description:
      'Biomaterial Cortante obtido de mobs. Uso: Crafting por família de slot.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Biomaterial Cortante',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Craniano Épico',
    slug: 'biomaterial-craniano-epico',
    description:
      'Biomaterial Craniano obtido de mobs. Uso: Crafting por família de slot.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Biomaterial Craniano',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial de Mobilidade Épico',
    slug: 'biomaterial-de-mobilidade-epico',
    description:
      'Biomaterial de Mobilidade obtido de mobs. Uso: Crafting por família de slot.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Biomaterial de Mobilidade',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Reativo Épico',
    slug: 'biomaterial-reativo-epico',
    description:
      'Biomaterial Reativo obtido de mobs. Uso: Crafting por família de slot.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Biomaterial Reativo',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Torácico Épico',
    slug: 'biomaterial-toracico-epico',
    description:
      'Biomaterial Torácico obtido de mobs. Uso: Crafting por família de slot.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Biomaterial Torácico',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Núcleo Infectado de Elite Épico',
    slug: 'nucleo-infectado-de-elite-epico',
    description:
      'Núcleo Infectado de Elite obtido de mobs. Uso: Crafting raro / upgrades de elite.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Núcleo Infectado de Elite',
    dropType: 'ELITE_CORE',
    usage: 'Crafting raro / upgrades de elite',
  },
  {
    name: 'Resíduo Infecto Mutagênico',
    slug: 'residuo-infecto-mutagenico',
    description:
      'Resíduo Infecto obtido de mobs. Uso: Crafting por faixa de tier.',
    tier: 7,
    rarity: Rarity.EPIC,
    family: 'Resíduo Infecto',
    dropType: 'RESIDUE',
    usage: 'Crafting por faixa de tier',
  },
  {
    name: 'Biomaterial Articular Lendário',
    slug: 'biomaterial-articular-lendario',
    description:
      'Biomaterial Articular obtido de mobs. Uso: Crafting por família de slot.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Biomaterial Articular',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Cortante Lendário',
    slug: 'biomaterial-cortante-lendario',
    description:
      'Biomaterial Cortante obtido de mobs. Uso: Crafting por família de slot.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Biomaterial Cortante',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial de Mobilidade Lendário',
    slug: 'biomaterial-de-mobilidade-lendario',
    description:
      'Biomaterial de Mobilidade obtido de mobs. Uso: Crafting por família de slot.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Biomaterial de Mobilidade',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Reativo Lendário',
    slug: 'biomaterial-reativo-lendario',
    description:
      'Biomaterial Reativo obtido de mobs. Uso: Crafting por família de slot.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Biomaterial Reativo',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Biomaterial Torácico Lendário',
    slug: 'biomaterial-toracico-lendario',
    description:
      'Biomaterial Torácico obtido de mobs. Uso: Crafting por família de slot.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Biomaterial Torácico',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
  {
    name: 'Núcleo Infectado de Elite Lendário',
    slug: 'nucleo-infectado-de-elite-lendario',
    description:
      'Núcleo Infectado de Elite obtido de mobs. Uso: Crafting raro / upgrades de elite.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Núcleo Infectado de Elite',
    dropType: 'ELITE_CORE',
    usage: 'Crafting raro / upgrades de elite',
  },
  {
    name: 'Resíduo Infecto Saturado',
    slug: 'residuo-infecto-saturado',
    description:
      'Resíduo Infecto obtido de mobs. Uso: Crafting por faixa de tier.',
    tier: 9,
    rarity: Rarity.LEGENDARY,
    family: 'Resíduo Infecto',
    dropType: 'RESIDUE',
    usage: 'Crafting por faixa de tier',
  },
  {
    name: 'Biomaterial Craniano Lendário',
    slug: 'biomaterial-craniano-lendario',
    description:
      'Biomaterial Craniano obtido de mobs. Uso: Crafting por família de slot.',
    tier: 10,
    rarity: Rarity.LEGENDARY,
    family: 'Biomaterial Craniano',
    dropType: 'BIOMATERIAL',
    usage: 'Crafting por família de slot',
  },
];

export const mobDropTables: MobDropTableSeedData[] = [
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Errante do Subúrbio',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Rato de Lixeira Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Cão de Rua Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Gato de Telhado Contaminado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Rastejante de Garagem',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Morador do Quintal',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Gambá de Entulho Contaminado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Morcego de Caixa d’Água',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Porteiro Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Inquilino Esticado do Bloco',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Urubu Carniceiro Contaminado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Síndico Devorado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Comum',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Carregador de Paletes Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Barata de Depósito Oleosa',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Operador de Empilhadeira Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Arrastador de Correntes',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Operário Prensado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Pistoneiro Hidráulico',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Lacraia de Esteira Ferruginosa',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Esmagado da Prensa',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Vigia do Galpão Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Soldador Mascarado Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Aranha de Viga Contaminada',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 2,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Capataz Ferrugento',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Comum',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Paciente Febril Errante',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Maqueiro Infectado',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Entubado da Triagem',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Mosca de Ferida Contaminada',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Enfermeira de Isolamento Infectada',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Técnico Selado de Descontaminação',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Interno Retorcido do Isolamento',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Centopeia de Tubulação Contaminada',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Instrumentador Cirúrgico Infectado',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Anestesista Colapsado',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Sanguessuga de Bolsa Hemática',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 3,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Cirurgião-Chefe Necrosado',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Incomum',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Amontoado de Bagagens Vivas',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Mandibulado do Embarque',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Farejador Mutado da Segurança',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Enxame de Carrapatos Hemáticos',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Sinaleiro Sem Rosto',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Corcunda do Bagageiro',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Verme de Escapamento Tóxico',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Casulo de Traças de Plataforma',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Cobrador Fundido',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Condutor Sem Mandíbula',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Escorpião de Painel Elétrico',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Incomum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 4,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Regente da Cabine Lacrada',
    rarity: Rarity.UNCOMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Amarelado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Incomum',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Isolado da Tenda Rasgada',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Cadáver de Maca Quarentenado',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Portador de Máscara Fundida',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Larva de Descarte Biológico',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Arameiro de Contenção',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Sentinela Eletrocutado',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Vazador Tóxico de Grade',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Lesma de Canaleta Química',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Operador de Rádio Infectado',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Oficial de Contenção Necrosado',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Parasita de Mesa Tática',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 5,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Coronel Lacrado da Zona 9',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Raro',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Homem-Tanque Rachado',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Afogado em Óleo Cinzento',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Salamandra de Borra Cinzenta',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Respirador de Cinzas',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Operário Escaldado de Vapor',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Queimado de Tubulação Viva',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Aracnídeo de Canos Ferventes',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Pressurizado Sem Face',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Forjado em Cinzas',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Carvoeiro Sem Pele',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Besta da Escória Fervente',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Raro',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 6,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Guardião da Fornalha Morta',
    rarity: Rarity.RARE,
    drops: [
      {
        itemName: 'Resíduo Infecto Tóxico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Raro',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Motorista Fundido ao Volante',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Buzinador Sem Cabeça',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Cervídeo Atropelado Mutado',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Colosso do Para-Choque',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Predador de Viela Cega',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Boca de Bueiro Faminta',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Corpo-Parede dos Becos',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Caçador de Neon Quebrado',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Semafórico de Carne Exposta',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Fendido do Asfalto',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Trauma de Sirene Quebrada',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 7,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Tirano do Cruzamento Morto',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Épico',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Observado de Vidro Vivo',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Técnico de Monitoração Fundido',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Olho Helix Suspenso',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Réplica Neural Incompleta',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Cobaia de Tanque Rompido',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Gêmeos de Cápsula Fundida',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Guardião de Acrílico Selado',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Larva de Amostra Helix',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Executivo Parasitado',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Arquivo Vivo Helix',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Assessor Biomecânico',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Épico',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 8,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Doutor Helix Primeiro Vetor',
    rarity: Rarity.EPIC,
    drops: [
      {
        itemName: 'Resíduo Infecto Mutagênico',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Épico',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Fundido de Escória Humana',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Mutilado de Metal Derretido',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Besouro de Fornalha Necrosado',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Colosso de Fuligem Coagulada',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Costurado da Esteira Morta',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Triturador de Membros Rejeitados',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Caranguejo de Sucata Orgânica',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Boneco de Cabos Nervosos',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Turbina de Carne Pulsante',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Forjado de Aço Necrosado',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Parasita de Caldeira Morta',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 9,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Soberano da Usina Morta',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Lendário',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Eco Humano Saturado',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Sentinela de Carne Cristalizada',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Cervical Aberta do Marco',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Lacraia de Cinza Primária',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial de Mobilidade Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Corpo Saturado de Mil Vozes',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Anjo de Pele Invertida',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Raiz Neural do Surto',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Besta de Radiação Orgânica',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Reativo Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
    mobName: 'Forma Primária do Surto',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Serafim do Colapso Biológico',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Cortante Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
    mobName: 'Carcaça do Primeiro Paciente',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Articular Lendário',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 10,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 4,
    mobType: 'ELITE',
    mobName: 'Coração do Marco Zero',
    rarity: Rarity.LEGENDARY,
    drops: [
      {
        itemName: 'Resíduo Infecto Saturado',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Núcleo Infectado de Elite Lendário',
        dropType: 'ELITE_CORE',
        dropChance: 25,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  // Registros legados inativos mantidos no banco por segurança do seed.
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
    mobName: 'Vizinho Infectado',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Torácico Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
  {
    tier: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
    mobName: 'Uivador de Varanda',
    rarity: Rarity.COMMON,
    drops: [
      {
        itemName: 'Resíduo Infecto Pálido',
        dropType: 'RESIDUE',
        dropChance: 45,
        minQuantity: 1,
        maxQuantity: 2,
      },
      {
        itemName: 'Biomaterial Craniano Comum',
        dropType: 'BIOMATERIAL',
        dropChance: 35,
        minQuantity: 1,
        maxQuantity: 1,
      },
    ],
  },
];
