import type { MobSeedData } from '../seed-types';
import { buildMobCombatStats, type MobType } from './mob-stats.seed-data';

export type MobBaseSeedData = {
  name: string;
  aliases?: string[];
  tier: number;
  level: number;
  mapName: string;
  subMapName: string;
  orderNoSubmap: number;
  mobType: MobType;
};

const ACTIVE_AUTO_COMBAT_ORDERS = new Set([1, 4]);

const ACTIVE_AUTO_COMBAT_GLOBAL_ORDERS = [1, 4, 5, 8, 9, 12] as const;

const ACTIVE_AUTO_COMBAT_WEIGHT_BY_RANK = [42, 24, 15, 9, 6, 4] as const;

export function isActiveAutoCombatMob(
  mob: Pick<MobBaseSeedData, 'orderNoSubmap'>,
) {
  return ACTIVE_AUTO_COMBAT_ORDERS.has(mob.orderNoSubmap);
}

export function getBaseAutoCombatEncounterWeight(
  mob: Pick<MobBaseSeedData, 'mobType' | 'orderNoSubmap'>,
) {
  if (!isActiveAutoCombatMob(mob)) return 0;

  return mob.mobType === 'ELITE'
    ? ACTIVE_AUTO_COMBAT_WEIGHT_BY_RANK[5]
    : ACTIVE_AUTO_COMBAT_WEIGHT_BY_RANK[0];
}

export function getAbsorbedAutoCombatMobOrder(
  mob: Pick<MobBaseSeedData, 'orderNoSubmap'>,
) {
  if (mob.orderNoSubmap === 1) return 2;
  if (mob.orderNoSubmap === 4) return 3;

  return null;
}

export function getActiveAutoCombatEncounterWeight(mob: MobBaseSeedData) {
  if (!isActiveAutoCombatMob(mob)) return 0;

  const rank = getActiveAutoCombatMobRank(mob);

  if (rank === null) return 0;

  return ACTIVE_AUTO_COMBAT_WEIGHT_BY_RANK[rank - 1] ?? 0;
}

export function getActiveAutoCombatMobRank(mob: MobBaseSeedData) {
  if (!isActiveAutoCombatMob(mob)) return null;

  const activeTierMobs = mobBaseDefinitions.filter(
    (candidate) =>
      candidate.tier === mob.tier && isActiveAutoCombatMob(candidate),
  );
  const index = activeTierMobs.findIndex(
    (candidate) =>
      candidate.name === mob.name &&
      candidate.mapName === mob.mapName &&
      candidate.subMapName === mob.subMapName,
  );

  if (index < 0) return null;

  return index + 1;
}

export function getActiveAutoCombatGlobalOrder(rank: number) {
  return ACTIVE_AUTO_COMBAT_GLOBAL_ORDERS[rank - 1] ?? null;
}

export const mobBaseDefinitions: MobBaseSeedData[] = [
  {
    name: 'Errante do Subúrbio',
    aliases: ['Errante Zumbi', 'Errante Suburbano'],
    tier: 1,
    level: 1,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Rato de Lixeira Infectado',
    aliases: ['Rato de Esgoto Inchado', 'Rato Infectado', 'Rato Inchado'],
    tier: 1,
    level: 2,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Cão de Rua Infectado',
    aliases: ['Cão Infectado', 'Cão de Rua'],
    tier: 1,
    level: 3,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Gato de Telhado Contaminado',
    aliases: ['Gato Infectado', 'Gato do Telhado'],
    tier: 1,
    level: 4,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Rua das Cercas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Rastejante de Garagem',
    aliases: ['Rastejante Infectado', 'Rastejante da Garagem'],
    tier: 1,
    level: 4,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Morador do Quintal',
    aliases: ['Morador Infectado', 'Morador do Quintal Abandonado'],
    tier: 1,
    level: 5,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Gambá de Entulho Contaminado',
    tier: 1,
    level: 6,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Morcego de Caixa d’Água',
    aliases: ['Morcego Contaminado', 'Morcego da Caixa D Água'],
    tier: 1,
    level: 7,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Quintais Abandonados',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Porteiro Infectado',
    aliases: ['Porteiro Zumbi', 'Porteiro do Bloco'],
    tier: 1,
    level: 7,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Inquilino Esticado do Bloco',
    aliases: [
      'Condômino Contorcido',
      'Condômino Infectado',
      'Contorcido do Bloco',
    ],
    tier: 1,
    level: 8,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Urubu Carniceiro Contaminado',
    aliases: ['Urubu Contaminado', 'Urubu Carniceiro'],
    tier: 1,
    level: 9,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Síndico Devorado',
    aliases: ['Síndico Infectado', 'Síndico do Bloco'],
    tier: 1,
    level: 10,
    mapName: 'Subúrbio Silencioso',
    subMapName: 'Bloco do Síndico',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Carregador de Paletes Infectado',
    tier: 2,
    level: 11,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Barata de Depósito Oleosa',
    tier: 2,
    level: 12,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Operador de Empilhadeira Infectado',
    tier: 2,
    level: 13,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Arrastador de Correntes',
    tier: 2,
    level: 14,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Pátio de Carga',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Operário Prensado',
    tier: 2,
    level: 14,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Pistoneiro Hidráulico',
    tier: 2,
    level: 15,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Lacraia de Esteira Ferruginosa',
    tier: 2,
    level: 16,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Esmagado da Prensa',
    tier: 2,
    level: 17,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Linha de Prensas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Vigia do Galpão Infectado',
    tier: 2,
    level: 17,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Soldador Mascarado Infectado',
    tier: 2,
    level: 18,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Aranha de Viga Contaminada',
    tier: 2,
    level: 19,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Capataz Ferrugento',
    tier: 2,
    level: 20,
    mapName: 'Distrito da Ferrugem',
    subMapName: 'Galpão do Capataz',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Paciente Febril Errante',
    tier: 3,
    level: 21,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Maqueiro Infectado',
    tier: 3,
    level: 22,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Entubado da Triagem',
    tier: 3,
    level: 23,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Mosca de Ferida Contaminada',
    tier: 3,
    level: 24,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Triagem Vazia',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Enfermeira de Isolamento Infectada',
    tier: 3,
    level: 24,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Técnico Selado de Descontaminação',
    tier: 3,
    level: 25,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Interno Retorcido do Isolamento',
    tier: 3,
    level: 26,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Centopeia de Tubulação Contaminada',
    tier: 3,
    level: 27,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Ala de Isolamento',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Instrumentador Cirúrgico Infectado',
    tier: 3,
    level: 27,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Anestesista Colapsado',
    tier: 3,
    level: 28,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Sanguessuga de Bolsa Hemática',
    tier: 3,
    level: 29,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Cirurgião-Chefe Necrosado',
    tier: 3,
    level: 30,
    mapName: 'Hospital Santa Ruína',
    subMapName: 'Centro Cirúrgico',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Amontoado de Bagagens Vivas',
    tier: 4,
    level: 31,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Mandibulado do Embarque',
    tier: 4,
    level: 32,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Farejador Mutado da Segurança',
    tier: 4,
    level: 33,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Enxame de Carrapatos Hemáticos',
    tier: 4,
    level: 34,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Saguão de Embarque',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Sinaleiro Sem Rosto',
    tier: 4,
    level: 34,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Corcunda do Bagageiro',
    tier: 4,
    level: 35,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Verme de Escapamento Tóxico',
    tier: 4,
    level: 36,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Casulo de Traças de Plataforma',
    tier: 4,
    level: 37,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Plataformas Mortas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Cobrador Fundido',
    tier: 4,
    level: 37,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Condutor Sem Mandíbula',
    tier: 4,
    level: 38,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Escorpião de Painel Elétrico',
    tier: 4,
    level: 39,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Regente da Cabine Lacrada',
    tier: 4,
    level: 40,
    mapName: 'Terminal dos Esquecidos',
    subMapName: 'Cabine Final',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Isolado da Tenda Rasgada',
    tier: 5,
    level: 41,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Cadáver de Maca Quarentenado',
    tier: 5,
    level: 42,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Portador de Máscara Fundida',
    tier: 5,
    level: 43,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Larva de Descarte Biológico',
    tier: 5,
    level: 44,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Triagem Externa',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Arameiro de Contenção',
    tier: 5,
    level: 44,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Sentinela Eletrocutado',
    tier: 5,
    level: 45,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Vazador Tóxico de Grade',
    tier: 5,
    level: 46,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Lesma de Canaleta Química',
    tier: 5,
    level: 47,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Cercas Internas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Operador de Rádio Infectado',
    tier: 5,
    level: 47,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Oficial de Contenção Necrosado',
    tier: 5,
    level: 48,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Parasita de Mesa Tática',
    tier: 5,
    level: 49,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Coronel Lacrado da Zona 9',
    tier: 5,
    level: 50,
    mapName: 'Zona de Quarentena 9',
    subMapName: 'Posto de Comando',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Homem-Tanque Rachado',
    tier: 6,
    level: 51,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Afogado em Óleo Cinzento',
    tier: 6,
    level: 52,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Salamandra de Borra Cinzenta',
    tier: 6,
    level: 53,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Respirador de Cinzas',
    tier: 6,
    level: 54,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tanques Vazios',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Operário Escaldado de Vapor',
    tier: 6,
    level: 54,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Queimado de Tubulação Viva',
    tier: 6,
    level: 55,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Aracnídeo de Canos Ferventes',
    tier: 6,
    level: 56,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Pressurizado Sem Face',
    tier: 6,
    level: 57,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Tubulação Quente',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Forjado em Cinzas',
    tier: 6,
    level: 57,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Carvoeiro Sem Pele',
    tier: 6,
    level: 58,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Besta da Escória Fervente',
    tier: 6,
    level: 59,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Guardião da Fornalha Morta',
    tier: 6,
    level: 60,
    mapName: 'Refinaria do Pó Cinzento',
    subMapName: 'Câmara da Fornalha',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Motorista Fundido ao Volante',
    tier: 7,
    level: 61,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Buzinador Sem Cabeça',
    tier: 7,
    level: 62,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Cervídeo Atropelado Mutado',
    tier: 7,
    level: 63,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Colosso do Para-Choque',
    tier: 7,
    level: 64,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Faixa Engarrafada',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Predador de Viela Cega',
    tier: 7,
    level: 64,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Boca de Bueiro Faminta',
    tier: 7,
    level: 65,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Corpo-Parede dos Becos',
    tier: 7,
    level: 66,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Caçador de Neon Quebrado',
    tier: 7,
    level: 67,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Becos de Caça',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Semafórico de Carne Exposta',
    tier: 7,
    level: 67,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Fendido do Asfalto',
    tier: 7,
    level: 68,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Trauma de Sirene Quebrada',
    tier: 7,
    level: 69,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Tirano do Cruzamento Morto',
    tier: 7,
    level: 70,
    mapName: 'Avenida dos Caídos',
    subMapName: 'Cruzamento Central',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Observado de Vidro Vivo',
    tier: 8,
    level: 71,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Técnico de Monitoração Fundido',
    tier: 8,
    level: 72,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Olho Helix Suspenso',
    tier: 8,
    level: 73,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Réplica Neural Incompleta',
    tier: 8,
    level: 74,
    mapName: 'Complexo Helix',
    subMapName: 'Ala de Observação',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Cobaia de Tanque Rompido',
    tier: 8,
    level: 74,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Gêmeos de Cápsula Fundida',
    tier: 8,
    level: 75,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Guardião de Acrílico Selado',
    tier: 8,
    level: 76,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Larva de Amostra Helix',
    tier: 8,
    level: 77,
    mapName: 'Complexo Helix',
    subMapName: 'Câmaras Seladas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Executivo Parasitado',
    tier: 8,
    level: 77,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Arquivo Vivo Helix',
    tier: 8,
    level: 78,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Assessor Biomecânico',
    tier: 8,
    level: 79,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Doutor Helix Primeiro Vetor',
    tier: 8,
    level: 80,
    mapName: 'Complexo Helix',
    subMapName: 'Diretoria Helix',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Fundido de Escória Humana',
    tier: 9,
    level: 81,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Mutilado de Metal Derretido',
    tier: 9,
    level: 82,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Besouro de Fornalha Necrosado',
    tier: 9,
    level: 83,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Colosso de Fuligem Coagulada',
    tier: 9,
    level: 84,
    mapName: 'Necrópole Industrial',
    subMapName: 'Pátio de Escória',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Costurado da Esteira Morta',
    tier: 9,
    level: 84,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Triturador de Membros Rejeitados',
    tier: 9,
    level: 85,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Caranguejo de Sucata Orgânica',
    tier: 9,
    level: 86,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Boneco de Cabos Nervosos',
    tier: 9,
    level: 87,
    mapName: 'Necrópole Industrial',
    subMapName: 'Esteiras Mortas',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Turbina de Carne Pulsante',
    tier: 9,
    level: 87,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Forjado de Aço Necrosado',
    tier: 9,
    level: 88,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Parasita de Caldeira Morta',
    tier: 9,
    level: 89,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Soberano da Usina Morta',
    tier: 9,
    level: 90,
    mapName: 'Necrópole Industrial',
    subMapName: 'Coração da Usina',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
  {
    name: 'Eco Humano Saturado',
    tier: 10,
    level: 91,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Sentinela de Carne Cristalizada',
    tier: 10,
    level: 92,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Cervical Aberta do Marco',
    tier: 10,
    level: 93,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Lacraia de Cinza Primária',
    tier: 10,
    level: 94,
    mapName: 'Marco Zero',
    subMapName: 'Anel Externo',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Corpo Saturado de Mil Vozes',
    tier: 10,
    level: 94,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Anjo de Pele Invertida',
    tier: 10,
    level: 95,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Raiz Neural do Surto',
    tier: 10,
    level: 96,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Besta de Radiação Orgânica',
    tier: 10,
    level: 97,
    mapName: 'Marco Zero',
    subMapName: 'Zona de Saturação',
    orderNoSubmap: 4,
    mobType: 'MONSTER',
  },
  {
    name: 'Forma Primária do Surto',
    tier: 10,
    level: 97,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 1,
    mobType: 'MONSTER',
  },
  {
    name: 'Serafim do Colapso Biológico',
    tier: 10,
    level: 98,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 2,
    mobType: 'MONSTER',
  },
  {
    name: 'Carcaça do Primeiro Paciente',
    tier: 10,
    level: 99,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 3,
    mobType: 'MONSTER',
  },
  {
    name: 'Coração do Marco Zero',
    tier: 10,
    level: 100,
    mapName: 'Marco Zero',
    subMapName: 'Núcleo do Colapso',
    orderNoSubmap: 4,
    mobType: 'ELITE',
  },
];

function buildMobDescription(mob: MobBaseSeedData): string {
  const role = mob.mobType === 'ELITE' ? 'Elite' : 'Ameaça';

  return (
    role +
    ' de Tier ' +
    mob.tier +
    ' encontrado em ' +
    mob.subMapName +
    ', no mapa ' +
    mob.mapName +
    '.'
  );
}

export const mobDefinitions: MobSeedData[] = mobBaseDefinitions.map((mob) => {
  const stats = buildMobCombatStats({
    tier: mob.tier,
    level: mob.level,
    mobName: mob.name,
    mobType: mob.mobType,
    autoCombatRank: getActiveAutoCombatMobRank(mob),
  });

  return {
    name: mob.name,
    aliases: mob.aliases,
    description: buildMobDescription(mob),
    ...stats,
    mapName: mob.mapName,
  };
});
