import type { MobSeedData } from '../seed-types';

export const mobDefinitions: MobSeedData[] = [
  {
    name: 'Errante do Subúrbio',
    aliases: ['Zumbi Errante', 'Errante Residencial'],
    description:
      'Humano zumbi. Ex-morador de rua residencial, com camiseta clara muito suja, bermuda velha e um tênis faltando. Corpo magro e torto, ombros caídos, braços soltos, mandíbula semiaberta, olhos leitosos e feridas pequenas de infecção inicial. Silhueta fraca, arrastada e desorganizada.',
    level: 1,
    tier: 1,
    hp: 45,
    attack: 7,
    defense: 2,
    speed: 3,
    xpReward: 7,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Vizinho Infectado',
    aliases: ['Vizinho Zumbi', 'Morador Infectado'],
    description:
      'Humano zumbi. Antigo morador reconhecível do bairro, usando camisa polo ou regata doméstica, calça de tecido ou short de casa e possível chinelo quebrado. Corpo mais encorpado que o Errante, barriga levemente saliente, postura mais firme, chaves penduradas, aliança ou relógio velho. Mordidas aparentes no pescoço e ombro.',
    level: 2,
    tier: 1,
    hp: 58,
    attack: 8,
    defense: 3,
    speed: 4,
    xpReward: 7,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Cão de Rua Infectado',
    aliases: ['Cão Infectado', 'Cachorro Infectado'],
    description:
      'Animal zumbi. Cachorro de médio porte, muito magro, com costelas aparentes, pelo falhado e sujo. Possui mordidas abertas no dorso, focinho ensanguentado e coleira velha arrebentada. Postura baixa e agressiva, patas dianteiras projetadas, boca aberta, saliva espessa e dentes irregulares.',
    level: 3,
    tier: 1,
    hp: 52,
    attack: 11,
    defense: 2,
    speed: 8,
    xpReward: 8,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Gato de Telhado Contaminado',
    aliases: ['Gato Contaminado', 'Gato de Telhado'],
    description:
      'Animal zumbi. Gato magro de corpo alongado, coluna arqueada, cauda falhada e pelo em tufos. Olhos brilhantes, orelha rasgada, unhas muito aparentes e expressão hostil. Visual ligado a telhados, quintais, fuligem e arranhões. Silhueta estreita, angular, rápida e inquieta.',
    level: 4,
    tier: 1,
    hp: 46,
    attack: 12,
    defense: 2,
    speed: 11,
    xpReward: 8,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Rastejante de Garagem',
    aliases: ['Rastejante', 'Infectado de Garagem'],
    description:
      'Humano zumbi. Corpo baixo, deformado e curvado para frente, como se tivesse perdido equilíbrio nas pernas ou sofrido trauma na coluna. Usa macacão de oficina rasgado, roupa engraxada ou restos de uniforme doméstico de trabalho. Arrasta uma perna, tem mãos sujas de graxa, unhas quebradas e rosto parcialmente escondido por cabelo oleoso.',
    level: 4,
    tier: 1,
    hp: 68,
    attack: 10,
    defense: 5,
    speed: 3,
    xpReward: 8,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Morador do Quintal',
    aliases: ['Zumbi do Quintal', 'Quintaleiro Infectado'],
    description:
      'Humano zumbi. Antigo morador ligado ao fundo da casa, horta, ferramentas, vasos, galinheiro e entulho. Usa camisa xadrez, avental velho, roupa de jardinagem ou luvas rasgadas. Corpo robusto, braços fortes sujos de terra, mordidas nos antebraços e costas. Diferente do Vizinho Infectado, transmite aparência de trabalhador doméstico do quintal.',
    level: 5,
    tier: 1,
    hp: 82,
    attack: 12,
    defense: 6,
    speed: 4,
    xpReward: 9,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Rato de Esgoto Inchado',
    aliases: ['Rato Infectado', 'Rato Inchado'],
    description:
      'Animal zumbi. Rato de tamanho acima do normal, corpo inchado, pele falhada, cauda ferida e barriga dilatada. Olhos pequenos e brilhantes, dentes exageradamente aparentes, manchas de lodo, sangue seco e pequenas áreas com carne exposta. Silhueta baixa, repulsiva e ligada à infestação.',
    level: 6,
    tier: 1,
    hp: 74,
    attack: 13,
    defense: 5,
    speed: 7,
    xpReward: 9,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Morcego de Caixa d’Água',
    aliases: ['Morcego Contaminado', 'Morcego Infectado'],
    description:
      'Animal zumbi. Morcego contaminado, com asas parcialmente rasgadas, membranas furadas, garras longas e cabeça ameaçadora. Pele úmida, corpo magro e expressão cadavérica. Ligado a forros, telhados, caixas d’água e áreas escuras. Menor, mais nervoso e mais sombrio que o Urubu Carniceiro.',
    level: 7,
    tier: 1,
    hp: 64,
    attack: 15,
    defense: 3,
    speed: 12,
    xpReward: 10,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Porteiro Infectado',
    aliases: ['Vigia Infectado', 'Porteiro Zumbi'],
    description:
      'Humano zumbi. Ex-porteiro ou vigia do prédio, usando uniforme de portaria destruído, camisa social amarrotada, colete de vigilância leve, rádio quebrado preso ao peito, crachá pendurado e molho de chaves no cinto. Corpo firme, postura de plantão e rosto cansado com feridas na mandíbula e testa.',
    level: 7,
    tier: 1,
    hp: 94,
    attack: 15,
    defense: 8,
    speed: 5,
    xpReward: 10,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Condômino Contorcido',
    aliases: ['Condômino Infectado', 'Contorcido do Bloco'],
    description:
      'Humanoide infectado. Criatura deformada originada de um condômino preso por muito tempo entre corredores, escadas e apartamentos fechados. Corpo alto, magro e torto, braços alongados, coluna curvada, dedos compridos e unhas quebradas. Usa restos de pijama, moletom, camiseta velha ou robe destruído. Mandíbula deslocada, olhos fundos e expressão de fome extrema.',
    level: 8,
    tier: 1,
    hp: 102,
    attack: 17,
    defense: 7,
    speed: 7,
    xpReward: 10,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Urubu Carniceiro Contaminado',
    aliases: ['Urubu Contaminado', 'Urubu Carniceiro'],
    description:
      'Animal zumbi. Ave grande, sombria e desagradável, com pescoço parcialmente nu, penas falhadas, sujeira, sangue seco e postura agressiva. Ligado a cadáveres em áreas abertas, lixo, terraços e janelas do bloco. Possui bico forte, asas grandes, garras visíveis, manchas esbranquiçadas de infecção e áreas de carne exposta.',
    level: 9,
    tier: 1,
    hp: 92,
    attack: 19,
    defense: 6,
    speed: 9,
    xpReward: 11,
    mapName: 'Subúrbio Silencioso',
  },
  {
    name: 'Síndico Devorado',
    aliases: ['Síndico Infectado', 'Elite do Bloco'],
    description:
      'Elite humano zumbi. Mini-chefe do Subúrbio Silencioso. Antigo síndico ou administrador do bloco, usando restos de camisa social, calça de alfaiataria, gravata frouxa, crachá, chaveiro de condomínio ou pasta de anotações presa ao corpo. Corpo largo e dominante, parcialmente mutilado, com marcas pesadas de mordida no tronco e no rosto. Representa a autoridade morta do condomínio.',
    level: 10,
    tier: 1,
    hp: 145,
    attack: 22,
    defense: 10,
    speed: 5,
    xpReward: 11,
    mapName: 'Subúrbio Silencioso',
  },
];