import { MissionType } from '@prisma/client';

export const missionDefinitions = [
  {
    key: 'story-first-supplies',
    title: 'Primeiros suprimentos',
    description: 'Colete 5 unidades de materiais para o abrigo.',
    type: MissionType.STORY,
    objectiveType: 'GATHER_UNITS',
    targetValue: 5,
    rewardXp: 80,
    rewardGold: 40,
    sortOrder: 10,
  },
  {
    key: 'daily-clear-threats',
    title: 'Limpeza diaria',
    description: 'Derrote 10 infectados em combate automatico.',
    type: MissionType.DAILY,
    objectiveType: 'DEFEAT_MOBS',
    targetValue: 10,
    rewardXp: 120,
    rewardGold: 70,
    sortOrder: 20,
  },
  {
    key: 'daily-field-crafting',
    title: 'Producao de campo',
    description: 'Conclua a fabricacao de 1 item.',
    type: MissionType.DAILY,
    objectiveType: 'CRAFT_ITEMS',
    targetValue: 1,
    rewardXp: 90,
    rewardGold: 55,
    sortOrder: 30,
  },
  {
    key: 'daily-incursion-return',
    title: 'Volta completa',
    description: 'Conclua 1 incursao com sucesso.',
    type: MissionType.DAILY,
    objectiveType: 'COMPLETE_INCURSIONS',
    targetValue: 1,
    rewardXp: 180,
    rewardGold: 100,
    sortOrder: 40,
  },
  {
    key: 'weekly-stockpile',
    title: 'Estoque semanal',
    description: 'Colete 100 unidades de materiais durante a semana.',
    type: MissionType.WEEKLY,
    objectiveType: 'GATHER_UNITS',
    targetValue: 100,
    rewardXp: 900,
    rewardGold: 500,
    sortOrder: 50,
  },
];

export const achievementDefinitions = [
  {
    key: 'survivor-level-5',
    title: 'Sobrevivente estabelecido',
    description: 'Alcance o nivel 5.',
    metricKey: 'CHARACTER_LEVEL',
    targetValue: 5,
    rewardCash: 5,
    sortOrder: 10,
  },
  {
    key: 'hunter-100',
    title: 'Cem ameacas a menos',
    description: 'Derrote 100 infectados.',
    metricKey: 'TOTAL_MOB_KILLS',
    targetValue: 100,
    rewardCash: 10,
    sortOrder: 20,
  },
  {
    key: 'maker-25',
    title: 'Oficina ativa',
    description: 'Produza 25 itens em crafting.',
    metricKey: 'TOTAL_CRAFTS',
    targetValue: 25,
    rewardCash: 10,
    sortOrder: 30,
  },
  {
    key: 'incursion-veteran-10',
    title: 'Veterano de expedicao',
    description: 'Conclua 10 incursoes com sucesso.',
    metricKey: 'TOTAL_INCURSIONS',
    targetValue: 10,
    rewardCash: 15,
    sortOrder: 40,
  },
];
