import { MissionType } from '@prisma/client';

export const missionDefinitions = [
  {
    key: 'story-first-supplies',
    title: 'Primeiros suprimentos',
    description: 'Colete 5 unidades de materiais para o abrigo.',
    type: MissionType.STORY,
    objectiveType: 'GATHER_UNITS',
    targetValue: 5,
    rewardXp: 80,
    rewardGold: 40,
    sortOrder: 10,
  },
  {
    key: 'daily-clear-threats',
    title: 'Limpeza diária',
    description: 'Derrote 10 infectados em combate automático.',
    type: MissionType.DAILY,
    objectiveType: 'DEFEAT_MOBS',
    targetValue: 10,
    rewardXp: 120,
    rewardGold: 70,
    sortOrder: 20,
  },
  {
    key: 'daily-field-crafting',
    title: 'Produção de campo',
    description: 'Conclua a fabricação de 1 item.',
    type: MissionType.DAILY,
    objectiveType: 'CRAFT_ITEMS',
    targetValue: 1,
    rewardXp: 90,
    rewardGold: 110,
    sortOrder: 30,
  },
  {
    key: 'daily-incursion-return',
    title: 'Volta completa',
    description: 'Conclua 1 incursão com sucesso.',
    type: MissionType.DAILY,
    objectiveType: 'COMPLETE_INCURSIONS',
    targetValue: 1,
    rewardXp: 180,
    rewardGold: 100,
    sortOrder: 40,
  },
  {
    key: 'weekly-stockpile',
    title: 'Estoque semanal',
    description: 'Colete 100 unidades de materiais durante a semana.',
    type: MissionType.WEEKLY,
    objectiveType: 'GATHER_UNITS',
    targetValue: 100,
    rewardXp: 900,
    rewardGold: 500,
    sortOrder: 50,
  },
  {
    key: 'weekly-clear-horde',
    title: 'Limpeza da semana',
    description:
      'Derrote 100 infectados em combate automático durante a semana.',
    type: MissionType.WEEKLY,
    objectiveType: 'DEFEAT_MOBS',
    targetValue: 100,
    rewardXp: 360,
    rewardGold: 210,
    sortOrder: 60,
  },
  {
    key: 'weekly-incursion-patrol',
    title: 'Rondas de incursão',
    description: 'Conclua 3 incursões com sucesso durante a semana.',
    type: MissionType.WEEKLY,
    objectiveType: 'COMPLETE_INCURSIONS',
    targetValue: 3,
    rewardXp: 360,
    rewardGold: 200,
    sortOrder: 70,
  },
  {
    key: 'monthly-stockpile',
    title: 'Reserva mensal',
    description: 'Colete 500 unidades de materiais durante o mês.',
    type: MissionType.MONTHLY,
    objectiveType: 'GATHER_UNITS',
    targetValue: 500,
    rewardXp: 2_700,
    rewardGold: 1_500,
    sortOrder: 80,
  },
  {
    key: 'monthly-eradication',
    title: 'Erradicação mensal',
    description:
      'Derrote 500 infectados em combate automático durante o mês.',
    type: MissionType.MONTHLY,
    objectiveType: 'DEFEAT_MOBS',
    targetValue: 500,
    rewardXp: 600,
    rewardGold: 350,
    sortOrder: 90,
  },
  {
    key: 'monthly-incursion-campaign',
    title: 'Campanha de incursões',
    description: 'Conclua 10 incursões com sucesso durante o mês.',
    type: MissionType.MONTHLY,
    objectiveType: 'COMPLETE_INCURSIONS',
    targetValue: 10,
    rewardXp: 540,
    rewardGold: 300,
    sortOrder: 100,
  },
];

export const achievementDefinitions = [
  {
    key: 'survivor-level-5',
    title: 'Sobrevivente estabelecido',
    description: 'Alcance o nivel 5.',
    metricKey: 'CHARACTER_LEVEL',
    targetValue: 5,
    rewardCash: 5,
    sortOrder: 10,
  },
  {
    key: 'hunter-100',
    title: 'Cem ameacas a menos',
    description: 'Derrote 100 infectados.',
    metricKey: 'TOTAL_MOB_KILLS',
    targetValue: 100,
    rewardCash: 10,
    sortOrder: 20,
  },
  {
    key: 'maker-25',
    title: 'Oficina ativa',
    description: 'Produza 25 itens em crafting.',
    metricKey: 'TOTAL_CRAFTS',
    targetValue: 25,
    rewardCash: 10,
    sortOrder: 30,
  },
  {
    key: 'incursion-veteran-10',
    title: 'Veterano de expedicao',
    description: 'Conclua 10 incursoes com sucesso.',
    metricKey: 'TOTAL_INCURSIONS',
    targetValue: 10,
    rewardCash: 15,
    sortOrder: 40,
  },
];
