INSERT INTO "mission_definitions" (
  "id",
  "key",
  "title",
  "description",
  "type",
  "objectiveType",
  "targetValue",
  "rewardXp",
  "rewardGold",
  "isActive",
  "sortOrder",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    gen_random_uuid()::text,
    'daily-clear-threats',
    'Limpeza diária',
    'Derrote 10 infectados em combate automático.',
    'DAILY',
    'DEFEAT_MOBS',
    10,
    120,
    70,
    true,
    20,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'daily-field-crafting',
    'Produção de campo',
    'Conclua a fabricação de 1 item.',
    'DAILY',
    'CRAFT_ITEMS',
    1,
    90,
    110,
    true,
    30,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'daily-incursion-return',
    'Volta completa',
    'Conclua 1 incursão com sucesso.',
    'DAILY',
    'COMPLETE_INCURSIONS',
    1,
    180,
    100,
    true,
    40,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'weekly-stockpile',
    'Estoque semanal',
    'Colete 100 unidades de materiais durante a semana.',
    'WEEKLY',
    'GATHER_UNITS',
    100,
    900,
    500,
    true,
    50,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'weekly-clear-horde',
    'Limpeza da semana',
    'Derrote 100 infectados em combate automático durante a semana.',
    'WEEKLY',
    'DEFEAT_MOBS',
    100,
    360,
    210,
    true,
    60,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'weekly-incursion-patrol',
    'Rondas de incursão',
    'Conclua 3 incursões com sucesso durante a semana.',
    'WEEKLY',
    'COMPLETE_INCURSIONS',
    3,
    360,
    200,
    true,
    70,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'monthly-stockpile',
    'Reserva mensal',
    'Colete 500 unidades de materiais durante o mês.',
    'MONTHLY',
    'GATHER_UNITS',
    500,
    2700,
    1500,
    true,
    80,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'monthly-eradication',
    'Erradicação mensal',
    'Derrote 500 infectados em combate automático durante o mês.',
    'MONTHLY',
    'DEFEAT_MOBS',
    500,
    600,
    350,
    true,
    90,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    gen_random_uuid()::text,
    'monthly-incursion-campaign',
    'Campanha de incursões',
    'Conclua 10 incursões com sucesso durante o mês.',
    'MONTHLY',
    'COMPLETE_INCURSIONS',
    10,
    540,
    300,
    true,
    100,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("key") DO UPDATE
SET
  "title" = EXCLUDED."title",
  "description" = EXCLUDED."description",
  "type" = EXCLUDED."type",
  "objectiveType" = EXCLUDED."objectiveType",
  "targetValue" = EXCLUDED."targetValue",
  "rewardXp" = EXCLUDED."rewardXp",
  "rewardGold" = EXCLUDED."rewardGold",
  "isActive" = EXCLUDED."isActive",
  "sortOrder" = EXCLUDED."sortOrder",
  "updatedAt" = CURRENT_TIMESTAMP;
