export type CosmeticVendorCategory =
  | 'avatar'
  | 'frame'
  | 'card'
  | 'overview'
  | 'effect'
  | 'identity';

export type CosmeticVendorCurrency = 'GOLD' | 'CASH';

export interface CosmeticVendorProductDefinition {
  id: string;
  category: CosmeticVendorCategory;
  name: string;
  description: string;
  currency: CosmeticVendorCurrency;
  price: number;
  cosmeticKeys: readonly string[];
  sortOrder: number;
}

export const COSMETIC_VENDOR_PRODUCTS = Object.freeze([
  {
    id: 'gold-avatar-vigia-oficina',
    category: 'avatar',
    name: 'Vigia da Oficina',
    description: 'Retrato masculino de um sobrevivente da manutenção.',
    currency: 'GOLD',
    price: 900,
    cosmeticKeys: ['avatar-acervo-vigia-oficina'],
    sortOrder: 10,
  },
  {
    id: 'gold-avatar-batedora-patio',
    category: 'avatar',
    name: 'Batedora do Pátio',
    description: 'Retrato feminino de uma batedora do abrigo.',
    currency: 'GOLD',
    price: 1_050,
    cosmeticKeys: ['avatar-acervo-batedora-patio'],
    sortOrder: 20,
  },
  {
    id: 'gold-frame-chapa-rebitada',
    category: 'frame',
    name: 'Chapa Rebitada',
    description: 'Moldura de metal reaproveitado com cantos reforçados.',
    currency: 'GOLD',
    price: 550,
    cosmeticKeys: ['moldura-acervo-chapa-rebitada'],
    sortOrder: 10,
  },
  {
    id: 'gold-frame-lona-marcada',
    category: 'frame',
    name: 'Lona Marcada',
    description: 'Acabamento de lona costurada usado no inventário.',
    currency: 'GOLD',
    price: 650,
    cosmeticKeys: ['moldura-acervo-lona-marcada'],
    sortOrder: 20,
  },
  {
    id: 'gold-card-bancada-manutencao',
    category: 'card',
    name: 'Bancada de Manutenção',
    description: 'Uma bancada simples e funcional para o cartão público.',
    currency: 'GOLD',
    price: 700,
    cosmeticKeys: ['banner-acervo-bancada-manutencao'],
    sortOrder: 10,
  },
  {
    id: 'gold-card-corredor-almoxarifado',
    category: 'card',
    name: 'Corredor do Almoxarifado',
    description: 'O corredor de suprimentos aplicado ao cartão público.',
    currency: 'GOLD',
    price: 800,
    cosmeticKeys: ['banner-acervo-corredor-almoxarifado'],
    sortOrder: 20,
  },
  {
    id: 'gold-overview-oficina-abrigo',
    category: 'overview',
    name: 'Oficina do Abrigo',
    description: 'Garagem de manutenção aplicada à visão geral.',
    currency: 'GOLD',
    price: 1_250,
    cosmeticKeys: ['fundo-acervo-oficina-abrigo'],
    sortOrder: 10,
  },
  {
    id: 'gold-overview-patio-triagem',
    category: 'overview',
    name: 'Pátio de Triagem',
    description: 'Área de separação de suprimentos para a visão geral.',
    currency: 'GOLD',
    price: 1_400,
    cosmeticKeys: ['fundo-acervo-patio-triagem'],
    sortOrder: 20,
  },
  {
    id: 'gold-effect-poeira-oficina',
    category: 'effect',
    name: 'Poeira de Oficina',
    description: 'Partículas discretas atravessam o cartão do personagem.',
    currency: 'GOLD',
    price: 650,
    cosmeticKeys: ['efeito-acervo-poeira-oficina'],
    sortOrder: 10,
  },
  {
    id: 'gold-effect-pulso-lanterna',
    category: 'effect',
    name: 'Pulso de Lanterna',
    description: 'Um facho suave percorre o perfil em intervalos regulares.',
    currency: 'GOLD',
    price: 750,
    cosmeticKeys: ['efeito-acervo-pulso-lanterna'],
    sortOrder: 20,
  },
  {
    id: 'gold-identity-mao-na-massa',
    category: 'identity',
    name: 'Mão na Massa',
    description: 'Título e distintivo para quem mantém o abrigo funcionando.',
    currency: 'GOLD',
    price: 450,
    cosmeticKeys: ['titulo-acervo-mao-na-massa', 'distintivo-acervo-mm'],
    sortOrder: 10,
  },
  {
    id: 'gold-identity-olho-vigia',
    category: 'identity',
    name: 'Olho de Vigia',
    description: 'Título e distintivo para quem protege o perímetro.',
    currency: 'GOLD',
    price: 550,
    cosmeticKeys: ['titulo-acervo-olho-vigia', 'distintivo-acervo-ov'],
    sortOrder: 20,
  },
  {
    id: 'cash-avatar-xerife-asfalto',
    category: 'avatar',
    name: 'Rick Grimes',
    description: 'Retrato Premium de Rick Grimes após anos na estrada.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['avatar-depois-da-lei-xerife-asfalto'],
    sortOrder: 110,
  },
  {
    id: 'cash-avatar-patrulheiro-ruina',
    category: 'avatar',
    name: 'Shane Walsh',
    description: 'Retrato Premium de Shane Walsh em patrulha de sobrevivência.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['avatar-depois-da-lei-patrulheiro-ruina'],
    sortOrder: 120,
  },
  {
    id: 'cash-frame-estrela-quebrada',
    category: 'frame',
    name: 'Estrela Quebrada',
    description: 'Metal de patrulha, bronze gasto e sinais de sobrevivência.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['moldura-depois-da-lei-estrela-quebrada'],
    sortOrder: 110,
  },
  {
    id: 'cash-frame-cerco-aco',
    category: 'frame',
    name: 'Cerco de Aço',
    description: 'Moldura Premium de contenção reforçada e luz fria.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['moldura-depois-da-lei-cerco-aco'],
    sortOrder: 120,
  },
  {
    id: 'cash-card-ultima-patrulha',
    category: 'card',
    name: 'Última Patrulha',
    description: 'Posto rodoviário abandonado aplicado ao cartão público.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['banner-depois-da-lei-ultima-patrulha'],
    sortOrder: 110,
  },
  {
    id: 'cash-card-patio-quarentena',
    category: 'card',
    name: 'Pátio da Quarentena',
    description: 'Complexo fortificado aplicado ao cartão público.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['banner-depois-da-lei-patio-quarentena'],
    sortOrder: 120,
  },
  {
    id: 'cash-overview-rodovia-silenciosa',
    category: 'overview',
    name: 'Rodovia Silenciosa',
    description: 'A rota de evacuação esquecida aplicada à visão geral.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['fundo-depois-da-lei-rodovia-silenciosa'],
    sortOrder: 110,
  },
  {
    id: 'cash-overview-refugio-colina',
    category: 'overview',
    name: 'Refúgio da Colina',
    description: 'Uma fazenda fortificada aplicada à visão geral.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['fundo-depois-da-lei-refugio-colina'],
    sortOrder: 120,
  },
  {
    id: 'cash-effect-cinzas-lei',
    category: 'effect',
    name: 'Cinzas da Lei',
    description: 'Brasas e cinzas douradas atravessam o perfil.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['efeito-depois-da-lei-cinzas-lei'],
    sortOrder: 110,
  },
  {
    id: 'cash-effect-pulso-cerco',
    category: 'effect',
    name: 'Pulso de Cerco',
    description: 'Luzes de alerta e faíscas percorrem o perfil.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['efeito-depois-da-lei-pulso-cerco'],
    sortOrder: 120,
  },
  {
    id: 'cash-identity-ultimo-xerife',
    category: 'identity',
    name: 'Último Xerife',
    description: 'Título e distintivo Premium de comando na estrada.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: [
      'titulo-depois-da-lei-ultimo-xerife',
      'distintivo-depois-da-lei-ux',
    ],
    sortOrder: 110,
  },
  {
    id: 'cash-identity-sem-recuo',
    category: 'identity',
    name: 'Sem Recuo',
    description: 'Título e distintivo Premium de quem sustenta o cerco.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: [
      'titulo-depois-da-lei-sem-recuo',
      'distintivo-depois-da-lei-sr',
    ],
    sortOrder: 120,
  },
  {
    id: 'cash-avatar-leon',
    category: 'avatar',
    name: 'Leon',
    description: 'Retrato Premium de Leon em operação sob chuva intensa.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['avatar-chuva-quarentena-leon'],
    sortOrder: 130,
  },
  {
    id: 'cash-frame-protocolo-rpd',
    category: 'frame',
    name: 'Protocolo R.P.D.',
    description: 'Aço operacional, branco gasto e alerta escarlate.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['moldura-chuva-quarentena-protocolo-rpd'],
    sortOrder: 130,
  },
  {
    id: 'cash-card-posto-emergencia',
    category: 'card',
    name: 'Posto de Emergência',
    description: 'Um posto operacional encharcado aplicado ao cartão público.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['banner-chuva-quarentena-posto-emergencia'],
    sortOrder: 130,
  },
  {
    id: 'cash-overview-cidade-encharcada',
    category: 'overview',
    name: 'Cidade Encharcada',
    description: 'Uma avenida isolada sob chuva aplicada à visão geral.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['fundo-chuva-quarentena-cidade-encharcada'],
    sortOrder: 130,
  },
  {
    id: 'cash-effect-chuva-quarentena',
    category: 'effect',
    name: 'Chuva de Quarentena',
    description: 'Gotas frias e reflexos escarlates atravessam o perfil.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: ['efeito-chuva-quarentena-tempestade'],
    sortOrder: 130,
  },
  {
    id: 'cash-identity-agente-quarentena',
    category: 'identity',
    name: 'Agente da Quarentena',
    description: 'Título e distintivo Premium para operações sob tempestade.',
    currency: 'CASH',
    price: 5,
    cosmeticKeys: [
      'titulo-chuva-quarentena-agente-quarentena',
      'distintivo-chuva-quarentena-aq',
    ],
    sortOrder: 130,
  },
] satisfies readonly CosmeticVendorProductDefinition[]);

export function getCosmeticVendorProduct(productId: string) {
  return COSMETIC_VENDOR_PRODUCTS.find((product) => product.id === productId);
}

export const COSMETIC_VENDOR_COSMETIC_KEYS = Object.freeze(
  Array.from(
    new Set(
      COSMETIC_VENDOR_PRODUCTS.flatMap((product) => product.cosmeticKeys),
    ),
  ),
);
